from __future__ import annotations

from statuses.base import Status
from statuses.general.shield_block import SHIELD_BLOCK_STATUS

CLERIC_KEY_ABILITY_CHOICES = ["wisdom"]
CLERIC_DOCTRINE_CHOICES = ["cloistered_cleric", "warpriest"]
CLERIC_FAVORED_WEAPON_CHOICES = [
    "crossbow",
    "dagger",
    "falchion",
    "fist",
    "glaive",
    "greataxe",
    "greatsword",
    "longbow",
    "longsword",
    "mace",
    "rapier",
    "scimitar",
    "scythe",
    "shortsword",
    "spiked_chain",
    "staff",
    "starknife",
    "trident",
    "warhammer",
    "whip",
]
CLERIC_FONT_CHOICES = ["heal", "harm"]
CLERIC_WEAPON_GROUPS = {
    "crossbow": "simple",
    "dagger": "simple",
    "falchion": "martial",
    "fist": "unarmed",
    "glaive": "martial",
    "greataxe": "martial",
    "greatsword": "martial",
    "longbow": "martial",
    "longsword": "martial",
    "mace": "simple",
    "rapier": "martial",
    "scimitar": "martial",
    "scythe": "martial",
    "shortsword": "martial",
    "spiked_chain": "martial",
    "staff": "simple",
    "starknife": "martial",
    "trident": "martial",
    "warhammer": "martial",
    "whip": "martial",
}

# Domeny i ich initial domain spells (Table 8-2).
CLERIC_DOMAIN_INITIAL_SPELLS = {
    "air": "pushing_gust",
    "ambition": "blind_ambition",
    "cities": "face_in_the_crowd",
    "confidence": "veil_of_confidence",
    "creation": "splash_of_art",
    "darkness": "cloak_of_shadow",
    "death": "deaths_call",
    "destruction": "cry_of_destruction",
    "dreams": "sweet_dream",
    "earth": "hurtling_stone",
    "family": "soothing_words",
    "fate": "read_fate",
    "fire": "fire_ray",
    "freedom": "unimpeded_stride",
    "healing": "healers_blessing",
    "indulgence": "overstuff",
    "knowledge": "scholarly_recollection",
    "luck": "bit_of_luck",
    "magic": "magics_vessel",
    "might": "athletic_rush",
    "moon": "moonbeam",
    "nature": "vibrant_thorns",
    "nightmares": "waking_nightmare",
    "pain": "savor_the_sting",
    "passion": "charming_touch",
    "perfection": "perfected_mind",
    "protection": "protectors_sacrifice",
    "secrecy": "forced_quiet",
    "sun": "dazzling_flash",
    "travel": "agile_feet",
    "trickery": "sudden_shift",
    "truth": "word_of_truth",
    "tyranny": "touch_of_obedience",
    "undeath": "touch_of_undeath",
    "water": "tidal_surge",
    "wealth": "appearance_of_wealth",
    "zeal": "weapon_surge",
    "custom_domain_a": "custom_domain_spell_a",
    "custom_domain_b": "custom_domain_spell_b",
    "custom_domain_c": "custom_domain_spell_c",
}

CLERIC_DOMAIN_DESCRIPTIONS = {
    "air": "You can control winds and the weather.",
    "ambition": "You strive to keep up with and outpace the competition.",
    "cities": "You have powers over urban environments and denizens.",
    "confidence": "You overcome your fear and project pride.",
    "creation": "You have divine abilities related to crafting and art.",
    "darkness": "You operate in the darkness and take away the light.",
    "death": "You have the power to end lives and destroy undead.",
    "destruction": "You are a conduit for divine devastation.",
    "dreams": "You have the power to enter and manipulate dreams.",
    "earth": "You control soil and stone.",
    "family": "You aid and protect your family and community more effectively.",
    "fate": "You see and understand hidden inevitabilities.",
    "fire": "You control flame.",
    "freedom": "You liberate yourself and others from shackles and constraints.",
    "healing": "Your healing magic is particularly potent.",
    "indulgence": "You feast mightily and can shake off the effects of overindulging.",
    "knowledge": "You receive divine insights.",
    "luck": "You're unnaturally lucky and keep out of harm's way.",
    "magic": "You perform the unexpected and inexplicable.",
    "might": "Your physical power is bolstered by divine strength.",
    "moon": "You command powers associated with the moon.",
    "nature": "You hold power over animals and plants.",
    "nightmares": "You fill minds with horror and dread.",
    "pain": "You punish those who displease you with the sharp sting of pain.",
    "passion": "You evoke passion, whether as love or lust.",
    "perfection": "You strive to perfect your mind, body, and spirit.",
    "protection": "You ward yourself and others.",
    "secrecy": "You protect secrets and keep them hidden.",
    "sun": "You harness the power of the sun and other light sources, and punish undead.",
    "travel": "You have power over movement and journeys.",
    "trickery": "You deceive others and cause mischief.",
    "truth": "You pierce lies and discover the truth.",
    "tyranny": "You wield power to rule and enslave others.",
    "undeath": "Your magic carries close ties to the undead.",
    "water": "You control water and bodies of water.",
    "wealth": "You hold power over wealth, trade, and treasure.",
    "zeal": "Your inner fire increases your combat prowess.",
    "custom_domain_a": "Custom domain A.",
    "custom_domain_b": "Custom domain B.",
    "custom_domain_c": "Custom domain C.",
}

CLERIC_DOMAIN_ADVANCED_SPELLS = {
    "air": "disperse_into_air",
    "ambition": "competitive_edge",
    "cities": "pulse_of_the_city",
    "confidence": "delusional_pride",
    "creation": "artistic_flourish",
    "darkness": "darkened_eyes",
    "death": "eradicate_undeath",
    "destruction": "destructive_aura",
    "dreams": "dreamers_call",
    "earth": "localized_quake",
    "family": "unity",
    "fate": "tempt_fate",
    "fire": "flame_barrier",
    "freedom": "word_of_freedom",
    "healing": "rebuke_death",
    "indulgence": "take_its_course",
    "knowledge": "know_the_enemy",
    "luck": "lucky_break",
    "magic": "mystic_beacon",
    "might": "enduring_might",
    "moon": "touch_of_the_moon",
    "nature": "natures_bounty",
    "nightmares": "shared_nightmare",
    "pain": "retributive_pain",
    "passion": "captivating_adoration",
    "perfection": "perfected_form",
    "protection": "protectors_sphere",
    "secrecy": "safeguard_secret",
    "sun": "positive_luminance",
    "travel": "travelers_transit",
    "trickery": "tricksters_twin",
    "truth": "glimpse_the_truth",
    "tyranny": "commanding_lash",
    "undeath": "malignant_sustenance",
    "water": "downpour",
    "wealth": "precious_metals",
    "zeal": "zeal_for_battle",
    "custom_domain_a": "custom_advanced_domain_spell_a",
    "custom_domain_b": "custom_advanced_domain_spell_b",
    "custom_domain_c": "custom_advanced_domain_spell_c",
}

CLERIC_DEITY_DIVINE_SKILL_CHOICES = {
    "abadar": ["society"],
    "asmodeus": ["deception"],
    "calistria": ["deception"],
    "cayden_cailean": ["athletics"],
    "desna": ["acrobatics"],
    "erastil": ["survival"],
    "gorum": ["athletics"],
    "gozreh": ["survival"],
    "iomedae": ["intimidation"],
    "irori": ["athletics"],
    "lamashtu": ["survival"],
    "nethys": ["arcana"],
    "norgorber": ["stealth"],
    "pharasma": ["medicine"],
    "rovagug": ["athletics"],
    "sarenrae": ["medicine"],
    "shelyn": ["crafting", "performance"],
    "torag": ["crafting"],
    "urgathoa": ["intimidation"],
    "zon_kuthon": ["intimidation"],
    "custom": ["religion", "diplomacy", "intimidation", "medicine", "society", "athletics", "crafting"],
}

CLERIC_DEITY_OPTIONS = {
    "abadar": {
        "favored_weapon": "crossbow",
        "favored_weapon_group": "simple",
        "font_options": ["heal", "harm"],
        "domain_choices": ["cities", "earth", "travel", "wealth"],
    },
    "asmodeus": {
        "favored_weapon": "mace",
        "favored_weapon_group": "simple",
        "font_options": ["harm"],
        "domain_choices": ["confidence", "fire", "trickery", "tyranny"],
    },
    "calistria": {
        "favored_weapon": "whip",
        "favored_weapon_group": "martial",
        "font_options": ["heal", "harm"],
        "domain_choices": ["pain", "passion", "secrecy", "trickery"],
    },
    "cayden_cailean": {
        "favored_weapon": "rapier",
        "favored_weapon_group": "martial",
        "font_options": ["heal"],
        "domain_choices": ["cities", "freedom", "indulgence", "might"],
    },
    "desna": {
        "favored_weapon": "starknife",
        "favored_weapon_group": "martial",
        "font_options": ["heal"],
        "domain_choices": ["dreams", "luck", "moon", "travel"],
    },
    "erastil": {
        "favored_weapon": "longbow",
        "favored_weapon_group": "martial",
        "font_options": ["heal"],
        "domain_choices": ["earth", "family", "nature", "wealth"],
    },
    "gorum": {
        "favored_weapon": "greatsword",
        "favored_weapon_group": "martial",
        "font_options": ["heal", "harm"],
        "domain_choices": ["confidence", "destruction", "might", "zeal"],
    },
    "gozreh": {
        "favored_weapon": "trident",
        "favored_weapon_group": "martial",
        "font_options": ["heal"],
        "domain_choices": ["air", "nature", "travel", "water"],
    },
    "iomedae": {
        "favored_weapon": "longsword",
        "favored_weapon_group": "martial",
        "font_options": ["heal"],
        "domain_choices": ["confidence", "might", "truth", "zeal"],
    },
    "irori": {
        "favored_weapon": "fist",
        "favored_weapon_group": "unarmed",
        "font_options": ["heal", "harm"],
        "domain_choices": ["knowledge", "might", "perfection", "truth"],
    },
    "lamashtu": {
        "favored_weapon": "falchion",
        "favored_weapon_group": "martial",
        "font_options": ["heal", "harm"],
        "domain_choices": ["family", "might", "nightmares", "trickery"],
    },
    "nethys": {
        "favored_weapon": "staff",
        "favored_weapon_group": "simple",
        "font_options": ["heal", "harm"],
        "domain_choices": ["destruction", "knowledge", "magic", "protection"],
    },
    "norgorber": {
        "favored_weapon": "shortsword",
        "favored_weapon_group": "martial",
        "font_options": ["harm"],
        "domain_choices": ["death", "secrecy", "trickery", "wealth"],
    },
    "pharasma": {
        "favored_weapon": "dagger",
        "favored_weapon_group": "simple",
        "font_options": ["heal"],
        "domain_choices": ["death", "fate", "healing", "knowledge"],
    },
    "rovagug": {
        "favored_weapon": "greataxe",
        "favored_weapon_group": "martial",
        "font_options": ["harm"],
        "domain_choices": ["air", "destruction", "earth", "zeal"],
    },
    "sarenrae": {
        "favored_weapon": "scimitar",
        "favored_weapon_group": "martial",
        "font_options": ["heal"],
        "domain_choices": ["fire", "healing", "sun", "truth"],
    },
    "shelyn": {
        "favored_weapon": "glaive",
        "favored_weapon_group": "martial",
        "font_options": ["heal"],
        "domain_choices": ["creation", "family", "passion", "protection"],
    },
    "torag": {
        "favored_weapon": "warhammer",
        "favored_weapon_group": "martial",
        "font_options": ["heal"],
        "domain_choices": ["creation", "earth", "family", "protection"],
    },
    "urgathoa": {
        "favored_weapon": "scythe",
        "favored_weapon_group": "martial",
        "font_options": ["harm"],
        "domain_choices": ["indulgence", "magic", "might", "undeath"],
    },
    "zon_kuthon": {
        "favored_weapon": "spiked_chain",
        "favored_weapon_group": "martial",
        "font_options": ["harm"],
        "domain_choices": ["ambition", "darkness", "destruction", "pain"],
    },
    "custom": {
        "favored_weapon": None,
        "favored_weapon_group": None,
        "font_options": ["heal", "harm"],
        "domain_choices": ["custom_domain_a", "custom_domain_b", "custom_domain_c"],
    },
}

CLERIC_SPELLS_PER_DAY = {
    1: {"cantrip": 5, "rank_1": 2},
    2: {"cantrip": 5, "rank_1": 3},
    3: {"cantrip": 5, "rank_1": 3, "rank_2": 2},
    4: {"cantrip": 5, "rank_1": 3, "rank_2": 3},
    5: {"cantrip": 5, "rank_1": 3, "rank_2": 3, "rank_3": 2},
    6: {"cantrip": 5, "rank_1": 3, "rank_2": 3, "rank_3": 3},
    7: {"cantrip": 5, "rank_1": 3, "rank_2": 3, "rank_3": 3, "rank_4": 2},
    8: {"cantrip": 5, "rank_1": 3, "rank_2": 3, "rank_3": 3, "rank_4": 3},
    9: {"cantrip": 5, "rank_1": 3, "rank_2": 3, "rank_3": 3, "rank_4": 3, "rank_5": 2},
    10: {"cantrip": 5, "rank_1": 3, "rank_2": 3, "rank_3": 3, "rank_4": 3, "rank_5": 3},
    11: {"cantrip": 5, "rank_1": 3, "rank_2": 3, "rank_3": 3, "rank_4": 3, "rank_5": 3, "rank_6": 2},
    12: {"cantrip": 5, "rank_1": 3, "rank_2": 3, "rank_3": 3, "rank_4": 3, "rank_5": 3, "rank_6": 3},
    13: {
        "cantrip": 5,
        "rank_1": 3,
        "rank_2": 3,
        "rank_3": 3,
        "rank_4": 3,
        "rank_5": 3,
        "rank_6": 3,
        "rank_7": 2,
    },
    14: {
        "cantrip": 5,
        "rank_1": 3,
        "rank_2": 3,
        "rank_3": 3,
        "rank_4": 3,
        "rank_5": 3,
        "rank_6": 3,
        "rank_7": 3,
    },
    15: {
        "cantrip": 5,
        "rank_1": 3,
        "rank_2": 3,
        "rank_3": 3,
        "rank_4": 3,
        "rank_5": 3,
        "rank_6": 3,
        "rank_7": 3,
        "rank_8": 2,
    },
    16: {
        "cantrip": 5,
        "rank_1": 3,
        "rank_2": 3,
        "rank_3": 3,
        "rank_4": 3,
        "rank_5": 3,
        "rank_6": 3,
        "rank_7": 3,
        "rank_8": 3,
    },
    17: {
        "cantrip": 5,
        "rank_1": 3,
        "rank_2": 3,
        "rank_3": 3,
        "rank_4": 3,
        "rank_5": 3,
        "rank_6": 3,
        "rank_7": 3,
        "rank_8": 3,
        "rank_9": 2,
    },
    18: {
        "cantrip": 5,
        "rank_1": 3,
        "rank_2": 3,
        "rank_3": 3,
        "rank_4": 3,
        "rank_5": 3,
        "rank_6": 3,
        "rank_7": 3,
        "rank_8": 3,
        "rank_9": 3,
    },
    19: {
        "cantrip": 5,
        "rank_1": 3,
        "rank_2": 3,
        "rank_3": 3,
        "rank_4": 3,
        "rank_5": 3,
        "rank_6": 3,
        "rank_7": 3,
        "rank_8": 3,
        "rank_9": 3,
        "rank_10": 1,
    },
    20: {
        "cantrip": 5,
        "rank_1": 3,
        "rank_2": 3,
        "rank_3": 3,
        "rank_4": 3,
        "rank_5": 3,
        "rank_6": 3,
        "rank_7": 3,
        "rank_8": 3,
        "rank_9": 3,
        "rank_10": 1,
    },
}

CLERIC_PROMPT = (
    "KEY ABILITY: WISDOM\n"
    "At 1st level, your class gives you an ability boost to Wisdom.\n"
    "HIT POINTS: 8 plus your Constitution Modifier\n\n"
    "INITIAL PROFICIENCIES:\n"
    "PERCEPTION\n"
    "Trained in Perception\n"
    "SAVING THROWS\n"
    "Trained in Fortitude\n"
    "Trained in Reflex\n"
    "Expert in Will\n"
    "SKILLS\n"
    "Trained in Religion\n"
    "Trained in a number of additional skills equal to 2 plus your Intelligence modifier\n"
    "ATTACKS\n"
    "Trained in simple weapons\n"
    "Trained in unarmed attacks\n"
    "DEFENSES\n"
    "Trained in unarmored defense\n\n"
    "DIVINE FONT:\n"
    "Podczas setupu wybierasz heal/harm zgodnie z deity (lub custom).\n"
    "Na poczatku scenariusza przygotowujesz czary zgodnie z tabela Cleric Spells per Day.\n"
    "Dodatkowo Divine Font dodaje sloty Heal/Harm na najwyzszym dostepnym ranku (1 + modyfikator Charyzmy).\n\n"
    "DOCTRINE:\n"
    "Cloistered Cleric: automatycznie dostajesz Domain Initiate.\n"
    "Warpriest: Shield Block, a dla favored weapon simple/unarmed takze Deadly Simplicity."
)


def ClericStatus() -> Status:
    """Class: Cleric (setup deity/doctrine/font + domeny + initial domain spells)."""
    return Status(
        id="cleric",
        label="Cleric",
        data={
            "ui_prompt": CLERIC_PROMPT,
            "class_hp": 8,
            "ui_choice_kind": "cleric_setup",
            "cleric_key_ability_choices": list(CLERIC_KEY_ABILITY_CHOICES),
            "cleric_doctrine_choices": list(CLERIC_DOCTRINE_CHOICES),
            "cleric_favored_weapon_choices": list(CLERIC_FAVORED_WEAPON_CHOICES),
            "cleric_font_choices": list(CLERIC_FONT_CHOICES),
            "cleric_weapon_groups": dict(CLERIC_WEAPON_GROUPS),
            "cleric_deity_choices": list(CLERIC_DEITY_OPTIONS.keys()),
            "cleric_deity_options": dict(CLERIC_DEITY_OPTIONS),
            "cleric_deity_skill_choices": dict(CLERIC_DEITY_DIVINE_SKILL_CHOICES),
            "cleric_domain_spell_placeholders": dict(CLERIC_DOMAIN_INITIAL_SPELLS),
            "cleric_spells_per_day": {level: dict(slots) for level, slots in CLERIC_SPELLS_PER_DAY.items()},
            "cleric_spell_tradition": "divine",
            "cleric_prepared_cantrips_at_level1": 5,
            "cleric_prepared_rank_1_slots_at_level1": 2,
            "set_actor_attrs": {"class_name": "cleric"},
            "grants_statuses": [SHIELD_BLOCK_STATUS],
        },
    )


CLERIC_STATUS = ClericStatus()

__all__ = [
    "CLERIC_KEY_ABILITY_CHOICES",
    "CLERIC_DOCTRINE_CHOICES",
    "CLERIC_FAVORED_WEAPON_CHOICES",
    "CLERIC_FONT_CHOICES",
    "CLERIC_WEAPON_GROUPS",
    "CLERIC_DOMAIN_INITIAL_SPELLS",
    "CLERIC_DOMAIN_DESCRIPTIONS",
    "CLERIC_DOMAIN_ADVANCED_SPELLS",
    "CLERIC_SPELLS_PER_DAY",
    "CLERIC_DEITY_DIVINE_SKILL_CHOICES",
    "CLERIC_DEITY_OPTIONS",
    "CLERIC_PROMPT",
    "ClericStatus",
    "CLERIC_STATUS",
]
