"""Action declarations and action resolution orchestration."""

from .attacks import (
    AreaSpellAttack,
    AttackMechanic,
    BasicAttack,
    MeleeAttack,
    OpportunityAttack,
    RangedAttack,
    ReadyAttack,
    SpellAttack,
    SpellAttackRoll,
    SpellSaveAttack,
    attack_mechanic_from_source,
    opportunity_attack_mechanic,
    ready_attack_mechanic,
)
from .base import ActionMechanic, ActionResource, CombatActionMechanic, ExplorationActionMechanic, MechanicScope, TargetingMode
from .catalog import (
    action_mechanic_payload,
    builtin_combat_mechanics,
    combat_action_mechanic_from_definition,
)
from .healing import CustomHealing, HealingMechanic, ItemHealing, SpellHealing, healing_mechanic_from_source
from .interactions import ObjectInteraction, SceneInteractionMechanic, object_interaction_mechanic
from .movement import BasicMove, DashAction, MovementMechanic, basic_move_mechanic, dash_mechanic
from .resolution import (
    ActionResourceResolution,
    ActionResourceResolver,
    AreaSpellConfirmation,
    AreaSpellDamageResolution,
    AreaSpellResolver,
    AreaSpellTargetDamage,
    AttackActionResolver,
    HealingActionResolution,
    HealingActionResolver,
    SingleTargetDamageResolution,
    SingleTargetSaveSpellConfirmation,
    SpellSaveAttackResolver,
)
from .turn_actions import (
    DefensiveAction,
    ConcentrationAction,
    DisengageAction,
    DodgeAction,
    HelpAction,
    ItemAction,
    ReadyAction,
    StrengthPotionAction,
    SupportAction,
    concentration_attack_bonus_mechanic,
    disengage_mechanic,
    dodge_mechanic,
    help_mechanic,
    ready_mechanic,
    strength_potion_mechanic,
)

__all__ = [
    "ActionMechanic",
    "ActionResource",
    "ActionResourceResolution",
    "ActionResourceResolver",
    "AreaSpellAttack",
    "AreaSpellConfirmation",
    "AreaSpellDamageResolution",
    "AreaSpellResolver",
    "AreaSpellTargetDamage",
    "AttackActionResolver",
    "AttackMechanic",
    "BasicAttack",
    "BasicMove",
    "CombatActionMechanic",
    "ConcentrationAction",
    "CustomHealing",
    "DashAction",
    "DefensiveAction",
    "DisengageAction",
    "DodgeAction",
    "ExplorationActionMechanic",
    "HealingActionResolution",
    "HealingActionResolver",
    "HealingMechanic",
    "HelpAction",
    "ItemAction",
    "ItemHealing",
    "MechanicScope",
    "MeleeAttack",
    "MovementMechanic",
    "ObjectInteraction",
    "OpportunityAttack",
    "RangedAttack",
    "ReadyAction",
    "ReadyAttack",
    "SceneInteractionMechanic",
    "SingleTargetDamageResolution",
    "SingleTargetSaveSpellConfirmation",
    "SpellAttack",
    "SpellAttackRoll",
    "SpellHealing",
    "SpellSaveAttack",
    "SpellSaveAttackResolver",
    "StrengthPotionAction",
    "SupportAction",
    "TargetingMode",
    "action_mechanic_payload",
    "attack_mechanic_from_source",
    "basic_move_mechanic",
    "builtin_combat_mechanics",
    "combat_action_mechanic_from_definition",
    "concentration_attack_bonus_mechanic",
    "dash_mechanic",
    "disengage_mechanic",
    "dodge_mechanic",
    "healing_mechanic_from_source",
    "help_mechanic",
    "object_interaction_mechanic",
    "opportunity_attack_mechanic",
    "ready_attack_mechanic",
    "ready_mechanic",
    "strength_potion_mechanic",
]
