"""D&D 5e rules primitives."""

from .attacks import AttackRollOutcome, AttackRollResult, resolve_attack_roll
from .abilities import ability_modifier, dexterity_modifier
from .checks import CheckResult, resolve_ability_check, resolve_saving_throw
from .dice import (
    D20RollInput,
    D20RollInstruction,
    D20RollRequest,
    D20RollResult,
    RollMode,
    RollModifier,
    RollModifierBreakdown,
    RollModifierType,
    build_modifier_breakdown,
    resolve_d20_roll,
    roll_instruction,
)
from .effects import (
    ActiveEffect,
    AdditionalEffectExpiration,
    EffectApplicationResult,
    EffectDuration,
    EffectEvent,
    EffectEventType,
    EffectExpirationResult,
    EffectSource,
    EffectSourceType,
    EffectStackingPolicy,
    apply_active_effect,
    effect_expiration_label,
    effect_summary_label,
    effect_value_label,
    expire_active_effects,
)
from .resting import (
    HitDieSpendResult,
    RestResult,
    RestType,
    complete_long_rest,
    complete_short_rest,
    spend_hit_die,
)

__all__ = [
    "AttackRollOutcome",
    "AttackRollResult",
    "ActiveEffect",
    "AdditionalEffectExpiration",
    "CheckResult",
    "D20RollInput",
    "D20RollInstruction",
    "D20RollRequest",
    "D20RollResult",
    "HitDieSpendResult",
    "EffectApplicationResult",
    "EffectDuration",
    "EffectEvent",
    "EffectEventType",
    "EffectExpirationResult",
    "EffectSource",
    "EffectSourceType",
    "EffectStackingPolicy",
    "RollMode",
    "RollModifier",
    "RollModifierBreakdown",
    "RollModifierType",
    "RestResult",
    "RestType",
    "ability_modifier",
    "apply_active_effect",
    "build_modifier_breakdown",
    "complete_long_rest",
    "complete_short_rest",
    "dexterity_modifier",
    "effect_expiration_label",
    "effect_summary_label",
    "effect_value_label",
    "expire_active_effects",
    "resolve_ability_check",
    "resolve_attack_roll",
    "resolve_d20_roll",
    "resolve_saving_throw",
    "roll_instruction",
    "spend_hit_die",
]
