"""Optional LLM adapters for game-master assistance."""

from .gm_classifier import (
    GmActionFlow,
    GmClassifierClient,
    GmClassifierProposal,
    GmClassifierRequest,
    GmConsequence,
    GmDeclarationAnalysis,
    GmDeclarationAnalysisType,
    GmDeclarationThreadEntry,
    GmIntentType,
    GmPreparationEffect,
    GmProposalValidationError,
    GmValidatedProposal,
    GeminiGmClassifierClient,
    GroqGmClassifierClient,
    PreparationEffectDuration,
    PreparationEffectType,
    build_gm_classifier_request,
    challenge_option_from_validated_proposal,
    validate_gm_declaration_analysis,
    validate_gm_classifier_proposal,
)
from .npc_interaction import (
    GeminiNpcInteractionClient,
    GroqNpcInteractionClient,
    NpcEffect,
    NpcFlagChange,
    NpcInteractionClient,
    NpcInteractionProposal,
    NpcInteractionRequest,
    NpcValidatedInteraction,
    build_npc_interaction_request,
    validate_npc_interaction_proposal,
)
from .prompts import PromptId, load_prompt

__all__ = [
    "GmClassifierClient",
    "GmActionFlow",
    "GmClassifierProposal",
    "GmClassifierRequest",
    "GmConsequence",
    "GmDeclarationAnalysis",
    "GmDeclarationAnalysisType",
    "GmDeclarationThreadEntry",
    "GmIntentType",
    "GmPreparationEffect",
    "GmProposalValidationError",
    "GmValidatedProposal",
    "GeminiGmClassifierClient",
    "GroqGmClassifierClient",
    "GeminiNpcInteractionClient",
    "GroqNpcInteractionClient",
    "NpcEffect",
    "NpcFlagChange",
    "NpcInteractionClient",
    "NpcInteractionProposal",
    "NpcInteractionRequest",
    "NpcValidatedInteraction",
    "PreparationEffectDuration",
    "PreparationEffectType",
    "build_npc_interaction_request",
    "build_gm_classifier_request",
    "challenge_option_from_validated_proposal",
    "validate_npc_interaction_proposal",
    "validate_gm_declaration_analysis",
    "validate_gm_classifier_proposal",
    "PromptId",
    "load_prompt",
]
