"""Physical player-interface contracts and printable asset generation."""

from .action_catalog import (
    CARD_ACTION_CATALOG,
    CURATED_CARD_OWNERS,
    CardActionDefinition,
    CardPhase,
    CardTriggerWindow,
    CombatCardRoute,
    card_action_definition,
    validate_card_phase,
)
from .qr_generation import GeneratedQrAsset, generate_decision_card_qr
from .qr_payload import (
    DECISION_CARD_QR_VERSION,
    OWNED_DECISION_CARD_QR_VERSION,
    ActorCardQrPayload,
    DecisionCardActionKind,
    DecisionCardQrPayload,
    build_decision_card_qr_payload,
    build_actor_card_qr_payload,
    normalize_decision_card_scanner_text,
    parse_decision_card_qr_payload,
    parse_actor_card_qr_payload,
)
from .universal_actions import (
    ScannedUniversalCard,
    UniversalCardAction,
    resolve_universal_card_scan,
)
from .hero_card_sheet import (
    HERO_CARD_SPECS,
    HeroCardPrintSpec,
    HeroCardSheetResult,
    generate_hero_card_sheet,
)
from .character_card_sets import (
    CHARACTER_DECKS,
    CharacterActionCardSpec,
    CharacterCardSetResult,
    CharacterDeckSpec,
    generate_character_sheet_bw_pdf,
    generate_combined_character_sheets_bw_pdf,
    generate_character_card_set_bw_test,
    generate_character_card_set,
    printable_action_cards,
    render_character_sheet_bw,
    render_character_action_card_bw_test,
    render_character_hero_card_bw_test,
)

__all__ = [
    "CARD_ACTION_CATALOG",
    "CURATED_CARD_OWNERS",
    "CardActionDefinition",
    "CardPhase",
    "CardTriggerWindow",
    "CombatCardRoute",
    "DECISION_CARD_QR_VERSION",
    "OWNED_DECISION_CARD_QR_VERSION",
    "ActorCardQrPayload",
    "DecisionCardActionKind",
    "DecisionCardQrPayload",
    "GeneratedQrAsset",
    "ScannedUniversalCard",
    "UniversalCardAction",
    "build_decision_card_qr_payload",
    "build_actor_card_qr_payload",
    "card_action_definition",
    "generate_decision_card_qr",
    "normalize_decision_card_scanner_text",
    "parse_decision_card_qr_payload",
    "parse_actor_card_qr_payload",
    "resolve_universal_card_scan",
    "HERO_CARD_SPECS",
    "HeroCardPrintSpec",
    "HeroCardSheetResult",
    "generate_hero_card_sheet",
    "CHARACTER_DECKS",
    "CharacterActionCardSpec",
    "CharacterCardSetResult",
    "CharacterDeckSpec",
    "generate_character_sheet_bw_pdf",
    "generate_combined_character_sheets_bw_pdf",
    "generate_character_card_set_bw_test",
    "generate_character_card_set",
    "printable_action_cards",
    "render_character_sheet_bw",
    "render_character_action_card_bw_test",
    "render_character_hero_card_bw_test",
    "validate_card_phase",
]
