"""Single-class character creation domain."""

from .builder import build_character, validate_character_draft
from .content import load_character_catalog, load_character_resources
from .leveling import CharacterLevelUpResult, LevelUpChoices, level_up_character
from .models import (
    ABILITY_IDS,
    CHARACTER_RECORD_SCHEMA_VERSION,
    STANDARD_ARRAY,
    AbilityScoreBonuses,
    BackgroundDefinition,
    CharacterBuildResources,
    CharacterCatalog,
    CharacterDraft,
    CharacterLevelDefinition,
    CharacterValidation,
    CharacterValidationIssue,
    ClassDefinition,
    ClassChoiceGroupDefinition,
    ClassOptionDefinition,
    CreatedCharacter,
    EquipmentPackage,
    ItemGrant,
    SpeciesDefinition,
    SpeciesVariantDefinition,
    SubclassDefinition,
)
from .point_buy import (
    POINT_BUY_BUDGET,
    POINT_BUY_COSTS,
    POINT_BUY_MAXIMUM,
    POINT_BUY_MINIMUM,
    PointBuySummary,
    summarize_point_buy,
)
from .serialization import (
    CHARACTER_RECORD_SCHEMA,
    CHARACTER_RULESET_ID,
    character_record_payload,
    created_character_from_payload,
)
from .srd_manifest import (
    SRD_CLASS_SUBCLASS_IDS,
    SRD_CLASS_SPELL_IDS,
    SRD_SPECIES_IDS,
    SRD_SPELL_IDS_BY_LEVEL,
    SrdCharacterCoverage,
    audit_srd_character_coverage,
)
from .implementation_audit import (
    CharacterImplementationAudit,
    FeatureImplementationKind,
    audit_character_implementation,
    catalog_feature_ids,
    feature_implementation_kind,
    table_assisted_feature_exceptions,
    table_assisted_feature_riders,
)
from .feature_help import (
    OriginFeatureCoverage,
    OriginFeatureHelp,
    OriginFeatureUseMode,
    all_origin_feature_help,
    audit_origin_feature_coverage,
    origin_feature_help,
)
from .class_feature_help import (
    ClassFeatureHelpCoverage,
    all_class_feature_help,
    audit_level_one_class_feature_help,
    class_feature_help,
)
from .choice_help import (
    CLASS_CHOICE_GROUP_HELP,
    FIGHTING_STYLE_HELP,
    SKILL_CHOICE_HELP,
    FightingStyleHelp,
    SkillChoiceHelp,
)
from .default_roster import all_default_character_drafts, default_character_drafts
from .boardgame_profiles import apply_boardgame_archetype
from .archetypes import (
    HERO_ARCHETYPES,
    HERO_ARCHETYPES_BY_ID,
    PLAYABLE_HERO_ARCHETYPES,
    PLAYABLE_HERO_IDS,
    HeroArchetype,
    hero_archetype,
)
from .assisted_spell_audit import (
    ASSISTED_SPELL_PLANS,
    AssistedSpellAudit,
    AssistedSpellFamily,
    AssistedSpellPlan,
    assisted_spell_plan,
    audit_assisted_spell_plans,
)
from .roster import (
    CharacterRoster,
    CharacterRosterError,
    CharacterRosterScan,
)

__all__ = [
    "ABILITY_IDS",
    "CHARACTER_RECORD_SCHEMA_VERSION",
    "CHARACTER_RECORD_SCHEMA",
    "CHARACTER_RULESET_ID",
    "STANDARD_ARRAY",
    "POINT_BUY_BUDGET",
    "POINT_BUY_COSTS",
    "POINT_BUY_MAXIMUM",
    "POINT_BUY_MINIMUM",
    "PointBuySummary",
    "AbilityScoreBonuses",
    "BackgroundDefinition",
    "CharacterBuildResources",
    "CharacterCatalog",
    "CharacterDraft",
    "CharacterLevelDefinition",
    "CharacterLevelUpResult",
    "CharacterValidation",
    "CharacterValidationIssue",
    "CharacterRoster",
    "CharacterRosterError",
    "CharacterRosterScan",
    "ClassDefinition",
    "ClassChoiceGroupDefinition",
    "ClassOptionDefinition",
    "CreatedCharacter",
    "EquipmentPackage",
    "ItemGrant",
    "LevelUpChoices",
    "SpeciesDefinition",
    "SpeciesVariantDefinition",
    "SubclassDefinition",
    "build_character",
    "character_record_payload",
    "created_character_from_payload",
    "load_character_catalog",
    "load_character_resources",
    "level_up_character",
    "validate_character_draft",
    "summarize_point_buy",
    "SRD_CLASS_SUBCLASS_IDS",
    "SRD_CLASS_SPELL_IDS",
    "SRD_SPECIES_IDS",
    "SRD_SPELL_IDS_BY_LEVEL",
    "SrdCharacterCoverage",
    "audit_srd_character_coverage",
    "CharacterImplementationAudit",
    "FeatureImplementationKind",
    "audit_character_implementation",
    "catalog_feature_ids",
    "feature_implementation_kind",
    "table_assisted_feature_exceptions",
    "table_assisted_feature_riders",
    "OriginFeatureHelp",
    "OriginFeatureCoverage",
    "OriginFeatureUseMode",
    "all_origin_feature_help",
    "audit_origin_feature_coverage",
    "origin_feature_help",
    "ClassFeatureHelpCoverage",
    "all_class_feature_help",
    "audit_level_one_class_feature_help",
    "class_feature_help",
    "CLASS_CHOICE_GROUP_HELP",
    "FIGHTING_STYLE_HELP",
    "SKILL_CHOICE_HELP",
    "FightingStyleHelp",
    "SkillChoiceHelp",
    "default_character_drafts",
    "all_default_character_drafts",
    "apply_boardgame_archetype",
    "HERO_ARCHETYPES",
    "HERO_ARCHETYPES_BY_ID",
    "PLAYABLE_HERO_ARCHETYPES",
    "PLAYABLE_HERO_IDS",
    "HeroArchetype",
    "hero_archetype",
    "ASSISTED_SPELL_PLANS",
    "AssistedSpellAudit",
    "AssistedSpellFamily",
    "AssistedSpellPlan",
    "assisted_spell_plan",
    "audit_assisted_spell_plans",
]
