"""Curated level-1 starter characters covering every supported class."""

from __future__ import annotations

from dnd_board_game.actors import AbilityScores

from .models import CharacterDraft


def default_character_drafts() -> tuple[CharacterDraft, ...]:
    return (
        CharacterDraft(
            id="brakka",
            name="Brakka",
            species_id="half_orc",
            class_id="barbarian",
            background_id="outlander",
            base_ability_scores=AbilityScores(15, 13, 14, 8, 12, 10),
            selected_skill_ids=("animal_handling", "perception"),
            equipment_package_id="barbarian_greataxe",
            selected_background_tool_ids=("drum",),
            selected_background_language_ids=("giant",),
            portrait="character_uploads/default_roster/brakka.png",
        ),
        CharacterDraft(
            id="lorian",
            name="Lorian",
            species_id="half_elf",
            class_id="bard",
            background_id="entertainer",
            base_ability_scores=AbilityScores(8, 14, 13, 12, 10, 15),
            selected_skill_ids=("deception", "persuasion", "stealth"),
            equipment_package_id="bard_diplomat",
            selected_cantrip_ids=("vicious_mockery", "mage_hand"),
            selected_spell_ids=(
                "healing_word",
                "faerie_fire",
                "thunderwave",
                "charm_person",
            ),
            selected_species_bonus_ability_ids=("dexterity", "constitution"),
            selected_species_skill_ids=("insight", "perception"),
            selected_species_language_ids=("dwarvish",),
            selected_class_option_ids=(
                "bard_instrument_lute",
                "bard_instrument_flute",
                "bard_instrument_viol",
            ),
            selected_background_tool_ids=("drum",),
            portrait="character_uploads/default_roster/lorian.png",
        ),
        CharacterDraft(
            id="dagna",
            name="Dagna",
            species_id="dwarf",
            class_id="cleric",
            background_id="acolyte",
            base_ability_scores=AbilityScores(13, 10, 14, 8, 15, 12),
            selected_skill_ids=("medicine", "persuasion"),
            equipment_package_id="cleric_guardian",
            selected_cantrip_ids=("sacred_flame", "guidance", "spare_the_dying"),
            selected_prepared_spell_ids=(
                "healing_word",
                "guiding_bolt",
                "shield_of_faith",
                "sanctuary",
            ),
            selected_subclass_id="life_domain",
            selected_species_tool_ids=("smiths_tools",),
            selected_background_language_ids=("celestial", "elvish"),
            portrait="character_uploads/default_roster/dagna.png",
        ),
        CharacterDraft(
            id="sylwen",
            name="Sylwen",
            species_id="elf",
            class_id="druid",
            background_id="hermit",
            base_ability_scores=AbilityScores(8, 13, 14, 12, 15, 10),
            selected_skill_ids=("nature", "survival"),
            equipment_package_id="druid_explorer",
            selected_cantrip_ids=("produce_flame", "guidance"),
            selected_prepared_spell_ids=("entangle", "goodberry", "healing_word"),
            selected_species_language_ids=("sylvan",),
            selected_species_cantrip_ids=("mage_hand",),
            selected_background_language_ids=("primordial",),
            portrait="character_uploads/default_roster/sylwen.png",
        ),
        CharacterDraft(
            id="garran",
            name="Garran",
            species_id="human",
            class_id="fighter",
            background_id="soldier",
            base_ability_scores=AbilityScores(15, 13, 14, 8, 12, 10),
            selected_skill_ids=("perception", "survival"),
            selected_fighting_style_id="defense",
            equipment_package_id="fighter_sword_and_board",
            selected_species_language_ids=("elvish",),
            selected_background_tool_ids=("dice_set",),
            portrait="character_uploads/default_roster/garran.png",
        ),
        CharacterDraft(
            id="pim",
            name="Pim",
            species_id="halfling",
            class_id="monk",
            background_id="urchin",
            base_ability_scores=AbilityScores(12, 15, 13, 10, 14, 8),
            selected_skill_ids=("acrobatics", "insight"),
            equipment_package_id="monk_staff",
            portrait="character_uploads/default_roster/pim.png",
        ),
        CharacterDraft(
            id="rhogar",
            name="Rhogar",
            species_id="dragonborn",
            class_id="paladin",
            background_id="noble",
            base_ability_scores=AbilityScores(15, 10, 13, 8, 12, 14),
            selected_skill_ids=("athletics", "religion"),
            equipment_package_id="paladin_guardian",
            selected_species_variant_id="red_dragon_ancestry",
            selected_background_tool_ids=("dragonchess_set",),
            selected_background_language_ids=("celestial",),
            portrait="character_uploads/default_roster/rhogar.png",
        ),
        CharacterDraft(
            id="erynd",
            name="Erynd",
            species_id="elf",
            class_id="ranger",
            background_id="folk_hero",
            base_ability_scores=AbilityScores(12, 15, 13, 10, 14, 8),
            selected_skill_ids=("investigation", "nature", "stealth"),
            equipment_package_id="ranger_archer",
            selected_species_language_ids=("sylvan",),
            selected_species_cantrip_ids=("light",),
            selected_class_option_ids=(
                "favored_enemy_beast",
                "natural_explorer_forest",
            ),
            selected_background_tool_ids=("woodcarvers_tools",),
            portrait="character_uploads/default_roster/erynd.png",
        ),
        CharacterDraft(
            id="mira",
            name="Mira",
            species_id="halfling",
            class_id="rogue",
            background_id="criminal",
            base_ability_scores=AbilityScores(8, 15, 13, 14, 12, 10),
            selected_skill_ids=(
                "acrobatics",
                "investigation",
                "perception",
                "sleight_of_hand",
            ),
            selected_expertise_ids=("stealth", "perception"),
            equipment_package_id="rogue_burglar",
            selected_background_tool_ids=("playing_card_set",),
            portrait="character_uploads/default_roster/mira.png",
        ),
        CharacterDraft(
            id="veyra",
            name="Veyra",
            species_id="tiefling",
            class_id="sorcerer",
            background_id="charlatan",
            base_ability_scores=AbilityScores(8, 13, 14, 10, 12, 15),
            selected_skill_ids=("arcana", "persuasion"),
            equipment_package_id="sorcerer_explorer",
            selected_cantrip_ids=(
                "fire_bolt",
                "mage_hand",
                "minor_illusion",
                "ray_of_frost",
            ),
            selected_spell_ids=("magic_missile", "shield"),
            selected_subclass_id="draconic_bloodline",
            portrait="character_uploads/default_roster/veyra.png",
        ),
        CharacterDraft(
            id="kael",
            name="Kael",
            species_id="half_elf",
            class_id="warlock",
            background_id="sage",
            base_ability_scores=AbilityScores(8, 13, 14, 10, 12, 15),
            selected_skill_ids=("deception", "intimidation"),
            equipment_package_id="warlock_scholar",
            selected_cantrip_ids=("eldritch_blast", "minor_illusion"),
            selected_spell_ids=("hellish_rebuke", "burning_hands"),
            selected_subclass_id="the_fiend",
            selected_species_bonus_ability_ids=("dexterity", "constitution"),
            selected_species_skill_ids=("perception", "persuasion"),
            selected_species_language_ids=("dwarvish",),
            selected_background_language_ids=("celestial", "draconic"),
            portrait="character_uploads/default_roster/kael.png",
        ),
        CharacterDraft(
            id="nimra",
            name="Nimra",
            species_id="gnome",
            class_id="wizard",
            background_id="sage",
            base_ability_scores=AbilityScores(8, 14, 13, 15, 12, 10),
            selected_skill_ids=("investigation", "insight"),
            equipment_package_id="wizard_scholar",
            selected_cantrip_ids=("fire_bolt", "mage_hand", "minor_illusion"),
            selected_spell_ids=(
                "magic_missile",
                "shield",
                "mage_armor",
                "detect_magic",
                "sleep",
                "find_familiar",
            ),
            selected_prepared_spell_ids=(
                "magic_missile",
                "shield",
                "mage_armor",
                "sleep",
            ),
            selected_background_language_ids=("elvish", "draconic"),
            portrait="character_uploads/default_roster/nimra.png",
        ),
    )


__all__ = ["default_character_drafts"]
