"""Scenario loading for encounter and exploration scenes."""

from .content_contract import (
    RULESET_DND_5E_2014,
    SCENARIO_SCHEMA,
    SCENARIO_SCHEMA_VERSION,
    ContentHeader,
    SourcePack,
    load_source_pack_registry,
    migrate_scenario_payload,
    validate_stable_id,
)
from .content_audit import (
    AuditSeverity,
    ContentAuditEntry,
    ContentAuditIssue,
    ContentAuditReport,
    audit_content,
)
from .catalog import ScenarioCatalogEntry, discover_scenarios
from .loader import (
    CompiledActorCombatContent,
    EncounterPartySizeVariant,
    LoadedExploration,
    LoadedEncounter,
    LoadedScenario,
    ScenarioActorDefinition,
    ScenarioAttackDefinition,
    ScenarioDefinition,
    ScenarioEnvironmentDefinition,
    ScenarioObjectiveDefinition,
    build_exploration_from_scenario,
    build_encounter_from_scenario,
    compile_actor_combat_content,
    encounter_with_custom_party,
    encounter_for_party_size,
    load_scenario,
)
from .preflight import ScenarioPreflightIssue, preflight_scenario

__all__ = [
    "AuditSeverity",
    "ContentAuditEntry",
    "ContentAuditIssue",
    "ContentAuditReport",
    "ContentHeader",
    "CompiledActorCombatContent",
    "EncounterPartySizeVariant",
    "LoadedEncounter",
    "LoadedExploration",
    "LoadedScenario",
    "RULESET_DND_5E_2014",
    "SCENARIO_SCHEMA",
    "SCENARIO_SCHEMA_VERSION",
    "ScenarioActorDefinition",
    "ScenarioAttackDefinition",
    "ScenarioCatalogEntry",
    "ScenarioDefinition",
    "ScenarioEnvironmentDefinition",
    "ScenarioObjectiveDefinition",
    "ScenarioPreflightIssue",
    "SourcePack",
    "build_encounter_from_scenario",
    "compile_actor_combat_content",
    "discover_scenarios",
    "encounter_with_custom_party",
    "encounter_for_party_size",
    "build_exploration_from_scenario",
    "audit_content",
    "load_scenario",
    "load_source_pack_registry",
    "migrate_scenario_payload",
    "preflight_scenario",
    "validate_stable_id",
]
