"""Export current printed cards and starter stats to the combat-only UI mock."""
from __future__ import annotations

from copy import deepcopy
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from dnd_board_game.character_creation.runes import apply_rune_profile
from dnd_board_game.physical_cards.character_card_sets import _starter_builds
from dnd_board_game.physical_cards.mana_print import build_print_hero
from dnd_board_game.scenarios.loader import compile_actor_combat_content
from dnd_board_game.scenarios.rune_charge_catalog import load_rune_charge_catalog
from dnd_board_game.ui.board_panel_symbols import rune_slot

OUTPUT = ROOT / "docs/ui/resonance-data.js"


def build_payload() -> dict[str, Any]:
    catalog = deepcopy(load_rune_charge_catalog())
    heroes = {}
    abilities = ("strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma")
    for hero_id, card_hero in catalog["heroes"].items():
        printed = build_print_hero(hero_id, rune_profile=True)
        actor = apply_rune_profile(_starter_builds()[1][hero_id][1].actor)
        source = next(s for s in compile_actor_combat_content(actor).attack_sources
                      if s.source_type.value == "weapon" and s.proficiency_id)
        stats = {key: row[2] for key, row in zip(abilities, printed.abilities)}
        weapon = dict(name=source.name, ability=source.ability,
                      kind=source.attack_kind.value, sides=source.damage_die_sides,
                      count=source.damage_components[0].dice.count,
                      damage_type=source.damage_type,
                      range=(source.range_feet or source.reach_feet or 5) // 5)
        for card in card_hero["cards"]:
            card["slot"] = rune_slot(card["rune"])
            for inflected, label in (("Siły", "Siła"), ("Mądrości", "Mądrość"),
                                     ("Charyzmy", "Charyzma"), ("Inteligencji", "Inteligencja")):
                card["effect"] = card["effect"].replace(
                    f"ST {inflected}", f"ST {catalog['rules']['save_dc_base']} + {label}")
        heroes[hero_id] = dict(**card_hero, id=hero_id, name=printed.name,
                              role=printed.role, maxHp=printed.hp, ac=printed.ac,
                              speed=printed.speed // 5, level=printed.level,
                              abilities=stats, weapon=weapon,
                              portrait=f"../../content/scenarios/misja_0_dzwon/assets/images/comic_v2/{hero_id}.png")
    return dict(version=1, rules=catalog["rules"], runes=catalog["runes"], heroes=heroes)


def render_data() -> str:
    return ("/* Generated by scripts/build_resonance_mock.py; mock only. */\n"
            "window.RESONANCE_DATA = " + json.dumps(build_payload(), ensure_ascii=False, indent=2) + ";\n")


if __name__ == "__main__":
    OUTPUT.write_text(render_data(), encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))
