from __future__ import annotations

import re


def _normalize(value: str | None) -> str:
    return str(value or "").strip().lower().replace("-", "_").replace(" ", "_")


_LABELS_PL: dict[str, str] = {
    # abilities
    "strength": "Sila",
    "dexterity": "Zrecznosc",
    "constitution": "Kondycja",
    "intelligence": "Inteligencja",
    "wisdom": "Madrosc",
    "charisma": "Charyzma",
    "free": "Dowolna",
    # core skills
    "acrobatics": "Akrobatyka",
    "arcana": "Arkana",
    "athletics": "Atletyka",
    "crafting": "Rzemioslo",
    "deception": "Oszustwo",
    "diplomacy": "Dyplomacja",
    "intimidation": "Zastraszanie",
    "medicine": "Medycyna",
    "nature": "Natura",
    "occultism": "Okultyzm",
    "performance": "Wystepy",
    "religion": "Religia",
    "society": "Spoleczenstwo",
    "stealth": "Skradanie",
    "survival": "Przetrwanie",
    "thievery": "Zlodziejstwo",
    "perception": "Percepcja",
    "fortitude": "Wytrzymalosc",
    "reflex": "Refleks",
    "will": "Wola",
    "untrained": "Niewyszkolony",
    "trained": "Wyszkolony",
    "expert": "Ekspert",
    "master": "Mistrz",
    "legendary": "Legendarny",
    # ancestries / classes
    "human": "Czlowiek",
    "elf": "Elf",
    "dwarf": "Krasnolud",
    "gnome": "Gnom",
    "goblin": "Goblin",
    "halfling": "Niziolek",
    "fighter": "Wojownik",
    "rogue": "Lotrzyk",
    "wizard": "Czarodziej",
    "cleric": "Kaplan",
    "barbarian": "Barbarzynca",
    "ranger": "Lowca",
    "bard": "Bard",
    "alchemist": "Alchemik",
    "alchemist_research_field": "Pole badan alchemika",
    "bomber": "Bombardier",
    "chirurgeon": "Chirurgion",
    "mutagenist": "Mutagenista",
    "champion": "Czempion",
    "paladin": "Paladyn",
    "redeemer": "Odkupiciel",
    "liberator": "Wyzwoliciel",
    "iomedae": "Iomedae",
    "sarenrae": "Sarenrae",
    "torag": "Torag",
    "shelyn": "Shelyn",
    "desna": "Desna",
    "abadar": "Abadar",
    "custom": "Wlasne",
    "druid": "Druid",
    "monk": "Mnich",
    "sorcerer": "Czarownik",
    # backgrounds
    "acolyte": "Akolita",
    "acrobat": "Akrobata",
    "animal_whisperer": "Szeptacz zwierzat",
    "artisan": "Rzemieslnik",
    "artist": "Artysta",
    "barkeep": "Karczmarz",
    "barrister": "Prawnik",
    "bounty_hunter": "Lowca nagrod",
    "charlatan": "Szarlatan",
    "criminal": "Przestepca",
    "detective": "Detektyw",
    "emissary": "Emisariusz",
    "entertainer": "Artysta sceniczny",
    "farmhand": "Pomocnik rolnika",
    "field_medic": "Medyk polowy",
    "fortune_teller": "Wrozbita",
    "gambler": "Hazardzista",
    "gladiator": "Gladiator",
    "guard": "Straznik",
    "herbalist": "Zielarz",
    "hermit": "Pustelnik",
    "hunter": "Lowca",
    "laborer": "Robotnik",
    "martial_disciple": "Uczen sztuk walki",
    "merchant": "Kupiec",
    "miner": "Gornik",
    "noble": "Szlachcic",
    "nomad": "Nomada",
    "prisoner": "Wiezien",
    "sailor": "Zeglarz",
    "scholar": "Uczony",
    "scout": "Zwiadowca",
    "street_urchin": "Ulicznik",
    "tinker": "Majsterkowicz",
    "warrior": "Wojownik",
    "background_acolyte": "Akolita",
    "background_acrobat": "Akrobata",
    "background_animal_whisperer": "Szeptacz zwierzat",
    "background_artisan": "Rzemieslnik",
    "background_artist": "Artysta",
    "background_barkeep": "Karczmarz",
    "background_barrister": "Prawnik",
    "background_bounty_hunter": "Lowca nagrod",
    "background_charlatan": "Szarlatan",
    "background_criminal": "Przestepca",
    "background_detective": "Detektyw",
    "background_emissary": "Emisariusz",
    "background_entertainer": "Artysta sceniczny",
    "background_farmhand": "Pomocnik rolnika",
    "background_field_medic": "Medyk polowy",
    "background_fortune_teller": "Wrozbita",
    "background_gambler": "Hazardzista",
    "background_gladiator": "Gladiator",
    "background_guard": "Straznik",
    "background_herbalist": "Zielarz",
    "background_hermit": "Pustelnik",
    "background_hunter": "Lowca",
    "background_laborer": "Robotnik",
    "background_martial_disciple": "Uczen sztuk walki",
    "background_merchant": "Kupiec",
    "background_miner": "Gornik",
    "background_noble": "Szlachcic",
    "background_nomad": "Nomada",
    "background_prisoner": "Wiezien",
    "background_sailor": "Zeglarz",
    "background_scholar": "Uczony",
    "background_scout": "Zwiadowca",
    "background_street_urchin": "Ulicznik",
    "background_tinker": "Majsterkowicz",
    "background_warrior": "Wojownik",
    # general feats
    "additional_lore": "Dodatkowa wiedza",
    "adopted_ancestry": "Przysposobiona Ancestry",
    "alchemical_crafting": "Alchemiczne rzemioslo",
    "arcane_sense": "Arcane Sense",
    "armor_proficiency": "Bieglosc w pancerzu",
    "assurance": "Pewnosc",
    "bargain_hunter": "Lowca okazji",
    "battle_medicine": "Medycyna polowa",
    "breath_control": "Kontrola oddechu",
    "canny_acumen": "Bystry umysl",
    "cat_fall": "Koci upadek",
    "charming_liar": "Uroczysty klamca",
    "combat_climber": "Bojowy wspinacz",
    "courtly_graces": "Dworska oglada",
    "diehard": "Twardziel",
    "dubious_knowledge": "Watpliwa wiedza",
    "experienced_professional": "Doswiadczony fachowiec",
    "experienced_smuggler": "Doswiadczony przemytnik",
    "experienced_tracker": "Doswiadczony tropiciel",
    "fascinating_performance": "Fascynujacy wystep",
    "fast_recovery": "Szybka regeneracja",
    "feather_step": "Lekki krok",
    "fleet": "Szybki krok",
    "forager": "Zbieracz",
    "group_coercion": "Grupowy przymus",
    "group_impression": "Grupowe wrazenie",
    "hefty_hauler": "Silny tragarz",
    "hobnobber": "Bywalec salonow",
    "impressive_performance": "Imponujacy wystep",
    "incredible_initiative": "Niezwykla inicjatywa",
    "intimidating_glare": "Grozne spojrzenie",
    "lengthy_diversion": "Dluga dywersja",
    "multilingual": "Poliglota",
    "natural_medicine": "Naturalna medycyna",
    "oddity_identification": "Identyfikacja osobliwosci",
    "pickpocket": "Kieszonkowiec",
    "quick_coercion": "Szybki przymus",
    "quick_identification": "Szybka identyfikacja",
    "quick_jump": "Szybki skok",
    "quick_repair": "Szybka naprawa",
    "quick_squeeze": "Szybkie przeciskanie",
    "read_lips": "Czytanie z ust",
    "recognize_spell": "Rozpoznanie czaru",
    "ride": "Jazda konna",
    "shield_block": "Blok tarcza",
    "sign_language": "Jezyk migowy",
    "skill_training": "Trening umiejetnosci",
    "snare_crafting": "Rzemioslo sidel",
    "specialty_crafting": "Specjalistyczne rzemioslo",
    "subtle_theft": "Subtelna kradziez",
    "survey_wildlife": "Obserwacja dzikiej przyrody",
    "terrain_expertise": "Znawca terenu",
    "terrain_stalker": "Lowca terenu",
    "titan_wrestler": "Pogromca olbrzymow",
    "toughness": "Wytrzymalosc",
    "train_animal": "Tresura zwierzat",
    "trick_magic_item": "Sztuczka z magicznym przedmiotem",
    "underwater_marauder": "Podwodny grabiezca",
    "virtuosic_performer": "Wirtuoz sceny",
    "weapon_proficiency": "Bieglosc w broni",
    # common action/event labels
    "move": "Ruch",
    "interaction": "Interakcja",
    "interact": "Interakcja",
    "seek": "Szukaj",
    "stealth": "Skradanie",
    "attack": "Atak",
    "equip": "Ekwipunek",
    "end": "Koniec tury",
    "delay": "Opoznij",
    "swap_weapon": "Zmiana broni",
    "unarmed": "Walka bez broni",
    "club": "Maczuga",
    "crossbow": "Kusza",
    "dagger": "Sztylet",
    "glaive": "Glewia",
    "greataxe": "Wielki topor",
    "halberd": "Halabarda",
    "javelin": "Oszczep",
    "light_crossbow": "Lekka kusza",
    "longbow": "Dlugi luk",
    "longsword": "Dlugi miecz",
    "mace": "Buzdygan",
    "rapier": "Rapier",
    "shortbow": "Krotki luk",
    "shortsword": "Krotki miecz",
    "spear": "Wlocznia",
    "sword": "Miecz",
    "warhammer": "Mlot wojenny",
    "gauntlet": "Rekawica bojowa",
    "spiked_gauntlet": "Kolczasta rekawica",
    "sickle": "Sierp",
    "staff": "Kostur",
    "bo_staff": "Kij bo",
    "dart": "Rzutka",
    "blowgun": "Dmuchawka",
    "sling": "Proca",
    "halfling_sling_staff": "Niziolecka proca-kostur",
    "battle_axe": "Topor bitewny",
    "bastard_sword": "Miecz bastardowy",
    "clan_dagger": "Sztylet klanowy",
    "katar": "Katar",
    "light_mace": "Lekki buzdygan",
    "longspear": "Dluga wlocznia",
    "flail": "Korbacz",
    "war_flail": "Korbacz wojenny",
    "morningstar": "Gwiazda poranna",
    "pick": "Kilof bojowy",
    "light_pick": "Lekki kilof",
    "greatpick": "Wielki kilof",
    "scimitar": "Sejmitar",
    "falchion": "Falchion",
    "greatclub": "Wielka maczuga",
    "guisarme": "Gisarma",
    "hatchet": "Toporek",
    "lance": "Lanca",
    "light_hammer": "Lekki mlot",
    "main_gauche": "Main-gauche",
    "ranseur": "Ranseur",
    "sap": "Palka",
    "scythe": "Kosa bojowa",
    "starknife": "Starknife",
    "shield_bash": "Uderzenie tarcza",
    "shield_boss": "Umbo tarczy",
    "shield_spikes": "Kolce tarczy",
    "trident": "Trojzab",
    "whip": "Bicz",
    "greatsword": "Wielki miecz",
    "maul": "Wielki mlot",
    "hand_crossbow": "Reczna kusza",
    "heavy_crossbow": "Ciezka kusza",
    "composite_shortbow": "Kompozytowy krotki luk",
    "composite_longbow": "Kompozytowy dlugi luk",
    "shuriken": "Shuriken",
    "dogslicer": "Psie ostrze",
    "elven_curve_blade": "Elfickie zakrzywione ostrze",
    "filchers_fork": "Widelec zlodzieja",
    "gnome_hooked_hammer": "Gnomi hakowy mlot",
    "horsechopper": "Koniorab",
    "kama": "Kama",
    "katana": "Katana",
    "kukri": "Kukri",
    "nunchaku": "Nunchaku",
    "orc_knuckle_dagger": "Orczy piesciowy sztylet",
    "sai": "Sai",
    "spiked_chain": "Kolczasty lancuch",
    "temple_sword": "Miecz swiatynny",
    "dwarven_waraxe": "Krasnoludzki topor wojenny",
    "gnome_flickmace": "Gnomi mlot cepowy",
    "orc_necksplitter": "Orczy przecinak karku",
    "sawtooth_saber": "Pila-szabla",
    "padded_armor": "Pikowany pancerz",
    "leather_armor": "Skorzana zbroja",
    "studded_leather": "Skorzana nabijana",
    "chain_shirt": "Koszula kolcza",
    "hide_armor": "Zbroja ze skor",
    "scale_mail": "Pancerz luskowy",
    "chain_mail": "Kolczuga",
    "breastplate": "Napiersnik",
    "splint_mail": "Pancerz lamelkowy",
    "half_plate": "Polzbroja plytowa",
    "full_plate": "Pelna zbroja plytowa",
    "buckler": "Puklerz",
    "wooden_shield": "Tarcza drewniana",
    "steel_shield": "Tarcza stalowa",
    "standard_shield": "Tarcza stalowa",
    "tower_shield": "Tarcza wiezowa",
    "arrows": "Strzaly (10)",
    "bolts": "Belty (10)",
    "sling_bullets": "Pociski do procy (10)",
    "backpack": "Plecak",
    "bedroll": "Poslanie",
    "belt_pouch": "Sakiewka na pas",
    "climbing_kit": "Zestaw wspinaczkowy",
    "chalk": "Kreda (10)",
    "crowbar": "Lom",
    "flint_and_steel": "Krzesiwo",
    "grappling_hook": "Hak zadziorny",
    "healer_tools": "Narzedzia medyka",
    "thieves_tools": "Narzedzia zlodziejskie",
    "repair_kit": "Zestaw naprawczy",
    "rope_hemp_50ft": "Lina konopna (50 ft)",
    "rope_silk_50ft": "Lina jedwabna (50 ft)",
    "rations_week": "Racje (1 tydzien)",
    "sack": "Worek",
    "torch": "Pochodnia",
    "waterskin": "Buklak",
    "lantern_hooded": "Latarnia kapturowa",
    "lantern_bullseye": "Latarnia reflektorowa",
    "oil_flask": "Olej (1 flaszka)",
    "spellbook": "Ksiega zaklec",
    "formula_book": "Ksiega formul",
    "caltrops": "Kolce",
    "chain_10ft": "Lancuch (10 ft)",
    "hammer": "Mlotek",
    "mirror_steel": "Lusterko stalowe",
    "soap": "Mydlo",
    "shovel": "Lopata",
    "signal_whistle": "Gwizdek sygnalowy",
    "spike_iron_10": "Zelazne kolki (10)",
    "lock_simple": "Zamek prosty",
    "lock_good": "Zamek dobry",
    "holy_symbol_wooden": "Swiety symbol (drewniany)",
    "holy_symbol_silver": "Swiety symbol (srebrny)",
    "writing_set": "Zestaw pisarski",
    "tent": "Namiot",
    "disarm": "Rozbrojenie",
    "parry": "Parowanie",
    "trip": "Podciecie",
    "shove": "Odepchniecie",
    "grapple": "Chwyt",
    "feint": "Zwod",
    "demoralize": "Demoralizacja",
    "aid": "Pomoc",
    "stand": "Wstan",
    "prone": "Padnij",
    "step": "Krok",
    "leap": "Skok",
    "take_cover": "Oslona",
    "cover": "Oslona",
    "raise_shield": "Podnies tarcze",
    "disable_device": "Rozbroj urzadzenie",
    "identify_trap": "Zidentyfikuj pulapke",
    "quick_alchemy": "Szybka alchemia",
    "mutagenic_flashback": "Mutageniczny flashback",
    "thunderstone": "Kamien gromu",
    "silvertongue_mutagen": "Mutagen srebrnego jezyka",
    "flurry_of_blows": "Grad ciosow",
    "rage": "Szal",
    "refocus": "Refokus",
    "skill_check": "Test umiejetnosci",
    "ancientblood": "Pradawna krew",
    "enemy_attack_melee": "Atak przeciwnika",
    "enemy_move": "Ruch przeciwnika",
    "phase_start_exploration": "Start eksploracji",
    "phase_end_exploration": "Koniec eksploracji",
    "phase_start_combat": "Start walki",
    "phase_end_combat": "Koniec walki",
    "lay_on_hands": "Nalozenie rak",
    "command_animal_companion": "Komenda: Zwierzecy towarzysz",
    "commandfamilair": "Komenda: Chowaniec",
    "hunt_prey": "Wyznacz ofiare",
    "drain_bonded_item": "Wyczerp bonded item",
    "drain_familiar": "Wyczerp chowańca",
    "wizard_spell_substitution": "Podmiana zaklecia",
    "retrain_sorcerer_spell": "Retrain Sorcerer Spell",
    "cancel": "Anuluj",
    # bombs / elixirs / poisons
    "acidflask": "Fiolka kwasu",
    "acid_flask": "Fiolka kwasu",
    "alchemists_fire": "Ognista mikstura alchemika",
    "bottled_lightning": "Butelkowana blyskawica",
    "frost_vial": "Mrozna fiolka",
    "tanglefoot_bag": "Worek lepikuli",
    "smokestick": "Dymna fiolka",
    "elixir_of_life": "Eliksir zycia",
    "holy_water": "Woda swiecona",
    "unholy_water": "Woda plugawa",
    "minor_healing_potion": "Mikstura leczenia (slaba)",
    "scroll_common_rank1": "Zwoj czaru 1. rangi",
    "potency_crystal": "Krysztal potencji",
    "cheetahs_elixir": "Eliksir geparda",
    "eagle_eye_elixir": "Eliksir sokolego oka",
    "juggernaut_mutagen": "Mutagen juggernauta",
    "quicksilver_mutagen": "Mutagen zywoksieci",
    "serene_mutagen": "Mutagen spokoju",
    "cognitive_mutagen": "Mutagen poznawczy",
    "antidote": "Antidotum",
    "antiplague": "Antyplaga",
    "arsenic": "Arsen",
    "giant_centipede_venom": "Jad wielkiej skolopendry",
    # human feats / heritages
    "half_elf": "Polelf",
    "half_orc": "Polork",
    "skilled_heritage": "Utalentowane dziedzictwo",
    "versatile_heritage": "Wszechstronne dziedzictwo",
    "general_training": "Trening ogolny",
    "natural_ambition": "Naturalna ambicja",
    "natural_skill": "Naturalny talent",
    "adapted_cantrip": "Adaptowany cantrip",
    "elf_atavism": "Elficki atawizm",
    "unconventional_weaponry": "Niekonwencjonalna bron",
    # common class feats (creation choices)
    "double_slice": "Podwojne ciecie",
    "exacting_strike": "Precyzyjny cios",
    "point_blank_shot": "Strzal z bliska",
    "power_attack": "Potezny atak",
    "reactive_shield": "Reaktywna tarcza",
    "snagging_strike": "Zaczepny cios",
    "sudden_charge": "Nagla szarza",
    "nimble_dodge": "Zwrotny unik",
    "trap_finder": "Tropiciel pulapek",
    "twin_feint": "Podwojna zwoda",
    "youre_next": "Ty jestes nastepny",
    "counterspell": "Kontrczar",
    "dangerous_sorcery": "Niebezpieczna czaroksieznosc",
    "familiar": "Chowaniec",
    "reach_spell": "Wydluzony czar",
    "widen_spell": "Poszerzony czar",
    "eschew_materials": "Rzucanie bez komponentow",
    "hand_of_the_apprentice": "Dlon adepta",
    "animal_companion": "Zwierzecy towarzysz",
    "crossbow_ace": "Mistrz kuszy",
    "hunted_shot": "Strzal na cel",
    "monster_hunter": "Lowca potworow",
    "twin_takedown": "Podwojne obalenie",
    "crane_stance": "Postawa zurawia",
    "dragon_stance": "Postawa smoka",
    "ki_rush": "Poryw ki",
    "ki_strike": "Uderzenie ki",
    "monastic_weaponry": "Bron klasztorna",
    "mountain_stance": "Postawa gory",
    "tiger_stance": "Postawa tygrysa",
    "wolf_stance": "Postawa wilka",
    "bardic_lore": "Bardyczna wiedza",
    "lingering_composition": "Trwala kompozycja",
    "versatile_performance": "Wszechstronny wystep",
    "deific_weapon": "Boska bron",
    "deitys_domain": "Domena bostwa",
    "ranged_reprisal": "Dystansowa reprymenda",
    "raise_shield_allow": "Podniesienie tarczy",
    "unimpeded_step": "Nieskrepowany krok",
    "weight_of_guilt": "Ciezar winy",
    "deadly_simplicity": "Smiercionosna prostota",
    "domain_initiate": "Inicjacja domeny",
    "harming_hands": "Dlonie krzywdy",
    "healing_hands": "Dlonie uzdrowienia",
    "holy_castigation": "Swiete zgromienie",
    "leshy_familiar": "Leshy chowaniec",
    "storm_born": "Zrodzony z burzy",
    "advanced_alchemy": "Zaawansowana alchemia",
    "alchemical_savant": "Alchemiczny wirtuoz",
    "alchemist_familiar_guidance": "Wsparcie chowańca alchemika",
    "far_lobber": "Daleki rzut",
    "quick_alchemy_allow": "Szybka alchemia",
    "quick_bomber": "Szybki bombardier",
    "cute_vision": "Czujne spojrzenie",
    "moment_of_clarity": "Moment jasnosci",
    "raging_intimidation": "Zastraszanie w szale",
    "raging_thrower": "Miotacz w szale",
    # ancestry feats (core set used in creation)
    "ancestral_longevity": "Pradawna dlugowiecznosc",
    "elven_lore": "Elficka wiedza",
    "elven_weapon_familiarity": "Elficka znajomosc broni",
    "forlorn": "Osamotniony",
    "nimble_elf": "Zwrotny elf",
    "otherworldly_magic": "Nadziemska magia",
    "unwavering_mien": "Niezachwiane oblicze",
    "dwarven_lore": "Krasnoludzka wiedza",
    "dwarven_weapon_familiarity": "Krasnoludzka znajomosc broni",
    "rock_runner": "Skalny biegacz",
    "stonecunning": "Kamienna bystrosc",
    "unburdened_iron": "Nieskrepowane zelazo",
    "vengeful_hatred": "Mscista nienawisc",
    "burn_it": "Podpal to",
    "city_scavenger": "Miejski padlinozerca",
    "goblin_lore": "Goblinska wiedza",
    "goblin_scuttle": "Goblini przemkniecie",
    "goblin_song": "Goblinska piesn",
    "goblin_weapon_familiarity": "Goblinska znajomosc broni",
    "junk_tinker": "Majsterkowicz zlomu",
    "rough_rider": "Szorstki jezdziec",
    "very_sneaky": "Bardzo skryty",
    "distracting_shadows": "Rozpraszajace cienie",
    "halfling_lore": "Niziolecka wiedza",
    "halfling_luck": "Szczescie niziolka",
    "halfling_weapon_familiarity": "Niziolecka znajomosc broni",
    "sure_feet": "Pewny krok",
    "titan_slinger": "Pogromca olbrzymow",
    "unfettered_halfling": "Nieskrepowany niziolek",
    "watchful_halfling": "Czujny niziolek",
    "animal_accomplice": "Zwierzecy pomocnik",
    "burrow_elocutionist": "Mowca nor",
    "fey_fellowship": "Wiez z fey",
    "first_world_magic": "Magia Pierwszego Swiata",
    "gnome_obsession": "Gnomia obsesja",
    "gnome_weapon_familiarity": "Gnomia znajomosc broni",
    "illusion_sense": "Zmysl iluzji",
    "orc_ferocity": "Orcza zajadlosc",
    "orc_sight": "Orczy wzrok",
    "orc_superstition": "Orczy przesad",
    "orc_weapon_familiarity": "Orcza znajomosc broni",
    "cooperative_nature": "Wspolpracujaca natura",
    "haughty_obstinacy": "Wyniosly upor",
    "monstrous_peacemaker": "Potworny rozjemca",
    # heritages
    "arctic_elf": "Arktyczny elf",
    "cavern_elf": "Jaskiniowy elf",
    "seer_elf": "Wizjonerski elf",
    "whisper_elf": "Szeptany elf",
    "woodland_elf": "Lesny elf",
    "ancient_blooded_dwarf": "Krasnolud pradawnej krwi",
    "forge_dwarf": "Kuzniany krasnolud",
    "rock_dwarf": "Skalny krasnolud",
    "strong_blooded_dwarf": "Krasnolud silnej krwi",
    "chameleon_gnome": "Kameleonowy gnom",
    "fey_touched_gnome": "Gnom dotkniety fey",
    "sensate_gnome": "Zmyslowy gnom",
    "umbral_gnome": "Mroczny gnom",
    "wellspring_gnome": "Gnom zrodla magii",
    "charhide_goblin": "Goblin o weglowej skorze",
    "irongut_goblin": "Goblin zelaznego zoladka",
    "razortooth_goblin": "Goblin o brzytwowych klach",
    "snow_goblin": "Sniezny goblin",
    "unbreakable_goblin": "Niezlomny goblin",
    "gutsy_halfling": "Niezwykle odwazny niziolek",
    "hillock_halfling": "Wzgorzowy niziolek",
    "nomadic_halfling": "Nomadyczny niziolek",
    "twilight_halfling": "Zmierzchowy niziolek",
    "wildwood_halfling": "Lesny niziolek",
    # magic traditions / schools / domains
    "arcane": "Arkana",
    "divine": "Boska",
    "occult": "Okultystyczna",
    "primal": "Pierwotna",
    "abjuration": "Abjuracja",
    "conjuration": "Konjuracja",
    "divination": "Dywinacja",
    "enchantment": "Zaklinanie",
    "evocation": "Ewokacja",
    "illusion": "Iluzja",
    "necromancy": "Nekromancja",
    "transmutation": "Transmutacja",
    "air": "Powietrze",
    "ambition": "Ambicja",
    "cities": "Miasta",
    "confidence": "Pewnosc",
    "creation": "Tworzenie",
    "darkness": "Ciemnosc",
    "death": "Smierc",
    "destruction": "Zniszczenie",
    "dreams": "Sny",
    "earth": "Ziemia",
    "family": "Rodzina",
    "fate": "Los",
    "fire": "Ogiec",
    "freedom": "Wolnosc",
    "healing": "Leczenie",
    "indulgence": "Folga",
    "knowledge": "Wiedza",
    "luck": "Szczescie",
    "magic": "Magia",
    "might": "Moc",
    "moon": "Ksiezyc",
    "nature": "Natura",
    "nightmares": "Koszmary",
    "pain": "Bol",
    "passion": "Pasja",
    "perfection": "Perfekcja",
    "protection": "Ochrona",
    "secrecy": "Sekretnosc",
    "sun": "Slonce",
    "travel": "Podroz",
    "trickery": "Podstep",
    "truth": "Prawda",
    "tyranny": "Tyrania",
    "undeath": "Niesmierc",
    "water": "Woda",
    "wealth": "Bogactwo",
    "zeal": "Gorliwosc",
    "custom_domain_a": "Domena niestandardowa A",
    "custom_domain_b": "Domena niestandardowa B",
    "custom_domain_c": "Domena niestandardowa C",
    # cantrips/spells
    "acid_splash": "Kwasowy rozprysk",
    "acidsplash": "Kwasowy rozprysk",
    "chill_touch": "Lodowy dotyk",
    "dancing_lights": "Tanczace swiatla",
    "daze": "Otumanienie",
    "detect_magic": "Wykrycie magii",
    "detectmagic": "Wykrycie magii",
    "disrupt_undead": "Zaklocenie nieumarlego",
    "divine_lance": "Boska lanca",
    "electric_arc": "Luk elektryczny",
    "forbidding_ward": "Zakazujaca oslona",
    "ghost_sound": "Widmowy dzwiek",
    "guidance": "Wskazowka",
    "know_direction": "Znajdz kierunek",
    "light": "Swiatlo",
    "mage_hand": "Magiczna dlon",
    "message": "Wiadomosc",
    "prestidigitation": "Sztuczki magiczne",
    "produce_flame": "Stworz plomien",
    "ray_of_frost": "Promien mrozu",
    "read_aura": "Odczyt aury",
    "shield": "Tarcza",
    "shield_cantrip": "Tarcza (cantrip)",
    "sigil": "Symbol",
    "stabilize": "Stabilizacja",
    "tanglefoot": "Lepliwe pnacza",
    "telekinetic_projectile": "Telekinetyczny pocisk",
    "air_bubble": "Babel powietrza",
    "alarm": "Alarm",
    "ant_haul": "Mrowi trud",
    "bane": "Nieszczescie",
    "bless": "Blogoslawienstwo",
    "burning_hands": "Plonace dlonie",
    "charm": "Urok",
    "color_spray": "Barwny rozblysk",
    "command": "Rozkaz",
    "create_water": "Stworz wode",
    "detect_alignment": "Wykrycie etosu",
    "detect_poison": "Wykrycie trucizny",
    "fear": "Strach",
    "feather_fall": "Lagodny upadek",
    "fleet_step": "Szybki krok",
    "floating_disk": "Latajacy dysk",
    "grease": "Smar",
    "grim_tendrils": "Ponure macki",
    "goblin_pox": "Goblinia zaraza",
    "gust_of_wind": "Podmuch wiatru",
    "harm": "Zranienie",
    "heal": "Uleczenie",
    "hydraulic_push": "Hydrauliczne pchniecie",
    "illusory_disguise": "Iluzoryczne przebranie",
    "illusory_object": "Iluzoryczny obiekt",
    "item_facade": "Fasada przedmiotu",
    "jump": "Skok",
    "lock": "Zaklucie",
    "longstrider": "Dlugi krok",
    "mage_armor": "Pancerz maga",
    "magic_aura": "Magiczna aura",
    "magic_fang": "Magiczny kiel",
    "magic_missile": "Magiczny pocisk",
    "magic_weapon": "Magiczna bron",
    "mending": "Naprawa",
    "mindlink": "Wiez umyslow",
    "negate_aroma": "Zneutralizuj zapach",
    "pass_without_trace": "Przejscie bez sladu",
    "pest_form": "Postac szkodnika",
    "phantom_pain": "Fantomowy bol",
    "purify_food_and_drink": "Oczysc jedzenie i napoj",
    "ray_of_enfeeblement": "Promien oslabenia",
    "shillelagh": "Shillelagh",
    "shocking_grasp": "Piorunujacy chwyt",
    "sleep": "Sen",
    "soothe": "Ukojenie",
    "spider_sting": "Pajecze uzadlenie",
    "spirit_link": "Wiez duchowa",
    "summon_animal": "Przywolaj zwierze",
    "summon_construct": "Przywolaj konstrukt",
    "summon_fey": "Przywolaj fey",
    "summon_plant": "Przywolaj rosline",
    "summon_plant_or_fungus": "Przywolaj rosline lub grzyb",
    "true_strike": "Prawdziwy cios",
    "unseen_servant": "Niewidzialny sluga",
    "ventriloquism": "Brzuchomowstwo",
    # focus/domain spells
    "agile_feet": "Zwinne stopy",
    "ancestral_memories": "Pamiec przodkow",
    "angelic_halo": "Anielska aureola",
    "appearance_of_wealth": "Pozor bogactwa",
    "athletic_rush": "Atletyczny zryw",
    "augment_summoning": "Wzmocnione przywolanie",
    "bit_of_luck": "Okruch szczescia",
    "blind_ambition": "Slepa ambicja",
    "call_of_the_grave": "Wezwanie grobu",
    "charming_touch": "Czarujacy dotyk",
    "charming_words": "Urzekajace slowa",
    "cloak_of_shadow": "Plaszcz cienia",
    "counter_performance": "Kontrwystep",
    "cry_of_destruction": "Krzyk zniszczenia",
    "custom_domain_spell_a": "Niestandardowy czar domeny A",
    "custom_domain_spell_b": "Niestandardowy czar domeny B",
    "custom_domain_spell_c": "Niestandardowy czar domeny C",
    "dazzling_flash": "Oslepiajacy blysk",
    "deaths_call": "Zew smierci",
    "diabolic_edict": "Diabelski edykt",
    "diviners_sight": "Wzrok wrozbity",
    "domain_focus_spell": "Czar skupienia domeny",
    "dragon_claws": "Smocze szpony",
    "elemental_toss": "Zywiolowy rzut",
    "face_in_the_crowd": "Twarz w tlumie",
    "faerie_dust": "Pyl fey",
    "fire_ray": "Promien ognia",
    "forced_quiet": "Wymuszona cisza",
    "force_bolt": "Pocisk mocy",
    "gluttons_jaws": "Szczeki obzarstwa",
    "goodberry": "Dobra jagoda",
    "heal_animal": "Ulecz zwierze",
    "healers_blessing": "Blogoslawienstwo uzdrowiciela",
    "hurtling_stone": "Pedzacy glaz",
    "inspire_competence": "Inspirujaca kompetencja",
    "inspire_courage": "Inspiracja odwagi",
    "jealous_hex": "Zaklecie zazdrosci",
    "ki_rush": "Poryw ki",
    "ki_strike": "Uderzenie ki",
    "loremaster_etude": "Etiuda loremastera",
    "magics_vessel": "Naczynie magii",
    "moonbeam": "Ksiezycowy promien",
    "overstuff": "Przejedzenie",
    "perfected_mind": "Udoskonalony umysl",
    "physical_boost": "Wzmocnienie fizyczne",
    "protective_ward": "Ochronna aura",
    "protectors_sacrifice": "Poswiecenie obroncy",
    "pushing_gust": "Pchajacy podmuch",
    "read_fate": "Odczyt losu",
    "savor_the_sting": "Delektuj sie uzadleniem",
    "scholarly_recollection": "Naukowe wspomnienie",
    "soothing_words": "Kojace slowa",
    "splash_of_art": "Rozprysk sztuki",
    "sudden_shift": "Nagla zmiana",
    "sweet_dream": "Slodki sen",
    "tempest_surge": "Poryw burzy",
    "tentacular_limbs": "Mackowate konczyny",
    "tidal_surge": "Przyplywowy zryw",
    "touch_of_obedience": "Dotyk posluszenstwa",
    "touch_of_undeath": "Dotyk niesmierci",
    "undeaths_blessing": "Blogoslawienstwo niesmierci",
    "unimpeded_stride": "Nieskrepowany krok",
    "veil_of_confidence": "Zaslona pewnosci",
    "vibrant_thorns": "Witalne ciernie",
    "waking_nightmare": "Przebudzony koszmar",
    "warped_terrain": "Wypaczony teren",
    "weapon_surge": "Zryw broni",
    "wild_morph": "Dzika mutacja",
    "wild_shape": "Dziki ksztalt",
    "word_of_truth": "Slowo prawdy",
    # additional bloodline granted spells (setup/localization)
    "abyssal_plague": "Otchlanna zaraza",
    "baleful_polymorph": "Zlowroga polimorfia",
    "bind_undead": "Zwiaz nieumarlego",
    "black_tentacles": "Czarne macki",
    "blindness": "Slepota",
    "blade_barrier": "Bariera ostrzy",
    "chromatic_wall": "Chromatyczna sciana",
    "cloak_of_colors": "Plaszcz kolorow",
    "cloudkill": "Trujaca chmura",
    "confusion": "Splatanie",
    "crushing_despair": "Przygniatajaca rozpacz",
    "dimension_door": "Wrota wymiaru",
    "disintegrate": "Dezintegracja",
    "dispel_magic": "Rozproszenie magii",
    "divine_aura": "Boska aura",
    "divine_decree": "Boski dekret",
    "divine_wrath": "Boski gniew",
    "dragon_form": "Smocza forma",
    "elemental_form": "Forma zywiolu",
    "energy_aegis": "Egida energii",
    "enlarge": "Powiekszenie",
    "enthrall": "Odurzenie",
    "false_life": "Falszywe zycie",
    "feeblemind": "Otumanienie umyslu",
    "finger_of_death": "Palec smierci",
    "fireball": "Kula ognia",
    "flame_strike": "Plomienny cios",
    "flaming_sphere": "Plomienna sfera",
    "foresight": "Przewidywanie",
    "freedom_of_movement": "Swoboda ruchu",
    "haste": "Przyspieszenie",
    "hideous_laughter": "Upiorny smiech",
    "horrid_wilting": "Potworne wysuszenie",
    "implosion": "Implozja",
    "mariners_curse": "Klatwa marynarza",
    "mask_of_terror": "Maska grozy",
    "maze": "Labirynt",
    "meteor_swarm": "Roj meteorow",
    "mislead": "Zwiedzenie",
    "natures_enmity": "Wrogosc natury",
    "outcasts_curse": "Klatwa wygnanca",
    "overwhelming_presence": "Przytlaczajaca obecnosc",
    "prismatic_sphere": "Pryzmatyczna sfera",
    "prismatic_spray": "Pryzmatyczny rozblysk",
    "prismatic_wall": "Pryzmatyczna sciana",
    "prying_eye": "Wscibskie oko",
    "repulsion": "Odepchniecie",
    "resist_energy": "Odpornosc na energie",
    "resplendent_mansion": "Olsniewajaca posiadlosc",
    "searing_light": "Palace swiatlo",
    "slow": "Spowolnienie",
    "spell_immunity": "Odpornosc na czar",
    "spiritual_epidemic": "Duchowa epidemia",
    "spiritual_weapon": "Duchowa bron",
    "storm_of_vengeance": "Burza zemsty",
    "suggestion": "Sugestia",
    "talking_corpse": "Mowiace zwloki",
    "touch_of_idiocy": "Dotyk idiotyzmu",
    "true_seeing": "Prawdziwe widzenie",
    "uncontrollable_dance": "Niekontrolowany taniec",
    "unfathomable_song": "Niezglebiona piesn",
    "vampiric_exsanguination": "Wampiryczne wykrwawienie",
    "vampiric_touch": "Wampiryczny dotyk",
    "visions_of_danger": "Wizje zagrozenia",
    "wail_of_the_banshee": "Lament banshee",
    "warp_mind": "Wypaczenie umyslu",
    # specialties / terrain picks
    "rubble": "Gruz",
    "snow": "Snieg",
    "underbrush": "Poszycie",
    "acting": "Aktorstwo",
    "comedy": "Komedia",
    "dance": "Taniec",
    "keyboards": "Instrumenty klawiszowe",
    "oratory": "Oratorstwo",
    "percussion": "Perkusja",
    "singing": "Spiew",
    "strings": "Instrumenty strunowe",
    "winds": "Instrumenty detne",
    "academia": "Akademia",
    "engineering": "Inzynieria",
    "legal": "Prawo",
    "mercantile": "Handel",
    "military": "Wojskowosc",
    "sailing": "Zeglarstwo",
    "underworld": "Podziemie",
    "warfare": "Wojna",
}


_HINTS_PL: dict[str, str] = {
    "move": "Przemiesc postac po planszy w zasiegu jej predkosci.",
    "attack": "Wykonaj Strike aktywna bronia; gra dolicza biegłość, atrybut, MAP i premie.",
    "equip": "Zarzadzaj aktywna bronia, pancerzem i tarcza.",
    "interaction": "Wejdz w interakcje z obiektem na planszy.",
    "seek": "Wypatruj ukrytych celow lub obiektow.",
    "stealth": "Ukryj sie / skradanie z modyfikatorami.",
    "delay": "Opoznij swoja ture w kolejnosci inicjatywy.",
    "end": "Zakonczy aktualna ture aktora.",
    "shield": "Podnies tarcze: +AC (circumstance) do poczatku kolejnej tury.",
    "raise_shield": "Podnies tarcze: +AC (circumstance) do poczatku kolejnej tury.",
    "disarm": "Probujesz rozbroic cel testem Athletics przeciwko jego obronie.",
    "trip": "Probujesz przewrocic cel testem Athletics.",
    "shove": "Probujesz odepchnac cel testem Athletics.",
    "grapple": "Probujesz pochwycic i unieruchomic cel.",
    "feint": "Zwodzisz cel, by ulatwic kolejny atak.",
    "demoralize": "Zastraszasz cel, by nalozyc Frightened.",
    "raise_shield": "Podnosisz tarcze i zyskujesz bonus do AC.",
    "take_cover": "Przyjmij oslone i zwieksz obrone.",
    "parry": "Akcja obronna: +1 circumstance do AC do poczatku nastepnej tury.",
    "power_attack": "Dwa ataki w cenie 2 akcji: Strike z dodatkowymi kosciami obrazen.",
    "exacting_strike": "Press: po nieudanym trafieniu lzej karze kolejne ataki (MAP).",
    "snagging_strike": "Strike melee z efektem off-guard na cel (wymaga wolnej reki).",
    "double_slice": "Dwa strike'i melee 1H na jednym celu; laczysz obrazenia przy 2 trafieniach.",
    "point_blank_shot": "Stance wojownika: premie dla atakow dystansowych na bliskim zasiegu.",
    "hunt_prey": "Oznacz cel lowow i aktywuj premie lowcy (Hunter's Edge).",
    "hunted_shot": "Dwa szybkie strzaly do oznaczonej ofiary (Hunt Prey).",
    "twin_takedown": "Dwa strike'i melee 1H przeciw oznaczonej ofierze.",
    "twin_feint": "Dwa strike'i melee 1H; drugi atak korzysta z feint/off-guard.",
    "sudden_charge": "2x ruch + strike melee w jednej akcji specjalnej (2 akcje).",
    "raging_intimidation": "Podczas Rage możesz używać Demoralize; dodatkowo otrzymujesz Intimidating Glare.",
    "enigma": "Muza barda: otrzymujesz Bardyczna wiedze i dopisujesz czar Prawdziwy cios.",
    "maestro": "Muza barda: otrzymujesz Trwala kompozycje i dopisujesz czar Ukojenie.",
    "polymath": "Muza barda: otrzymujesz Wszechstronny wystep i dopisujesz czar Niewidzialny sluga.",
    "flurry_of_blows": "Mnich: dwa uderzenia unarmed za 1 akcje (Flourish).",
    "rage": "Wejdz w Szal: premie ofensywne kosztem ograniczen i/lub obrony.",
    "refocus": "Odzyskaj punkt Focus poza presja walki.",
    "wizard_spell_substitution": (
        "Wizard (Spell Substitution): 10 minut poza walka, aby podmienic 1 niezuzyta kopie przygotowanego czaru "
        "na inny znany czar tej samej rangi. Limit: 1 raz na scenariusz."
    ),
    "retrain_sorcerer_spell": (
        "Sorcerer: podmienia 1 znany czar repertuaru na inny czar tej samej rangi z tej samej tradycji. "
        "Nie obejmuje bloodline granted spell."
    ),
    "skill_check": "Wykonaj test wybranej umiejetnosci z automatycznym doliczeniem premii.",
    "strength": "Sila: premia do atakow melee, Athletics i udzwigu.",
    "dexterity": "Zrecznosc: premia do atakow dystansowych, Reflex, AC i skradania.",
    "constitution": "Kondycja: wiecej HP i lepsze rzuty Fortitude.",
    "intelligence": "Inteligencja: wiecej trained skilli i lepsze testy wiedzy.",
    "wisdom": "Madrosc: lepsza Percepcja, Will i testy intuicyjne/medyczne.",
    "charisma": "Charyzma: silniejsze dzialania spoleczne i czesci magii.",
    "thunderstone": "Bomba: obrazenia sonic, splash i potencjalne ogluszenie.",
    "silvertongue_mutagen": "Mutagen: premie spoleczne kosztem parametrow fizycznych.",
    "quick_alchemy": "Tworzysz alchemiczny przedmiot w locie (wymaga feata i zasobow).",
    "bomber": (
        "Specjalizacja alchemika skupiona na bombach i precyzyjnym rozprysku. "
        "Mechanika: Signature items = acidflask i alchemists_fire; "
        "dla signature w Advanced Alchemy tworzysz 3 sztuki zamiast 2; "
        "rzucane bomby dostaja tryb wyboru splash ON/OFF (obszar albo tylko cel glowny)."
    ),
    "chirurgeon": (
        "Specjalizacja alchemika skupiona na leczeniu i medycynie polowej. "
        "Mechanika: Signature items = antidote i antiplague; "
        "w kanonie pozwala uzywac Crafting zamiast Medicine dla akcji medycznych; "
        "w silniku zapisujemy to jako znacznik research field (czesc zastosowan moze byc opisowa)."
    ),
    "mutagenist": (
        "Specjalizacja alchemika skupiona na mutagenach i ich ponownym wykorzystaniu. "
        "Mechanika: Signature items = quicksilver_mutagen i juggernaut_mutagen; "
        "dla signature w Advanced Alchemy tworzysz 3 sztuki zamiast 2; "
        "odblokowuje akcje Mutagenic Flashback (1 raz na dzien)."
    ),
    "mutagenic_flashback": "Raz dziennie odtworzenie efektu wypitego mutagenu (Mutagenist).",
    "command_animal_companion": "Wydajesz komende zwierzecemu towarzyszowi na jego 2 akcje.",
    "commandfamilair": "Wydajesz komende chowańcowi zgodnie z jego trybem.",
    "command_familiar": "Wydajesz komende chowańcowi zgodnie z jego trybem.",
    "lay_on_hands": "Focus spell czempiona: leczenie i tymczasowy bonus do AC.",
    "heal": (
        "Czar 1. rangi: wybierasz liczbe akcji przy rzucaniu.\n"
        "Mechanika:\n"
        "- 1 akcja (dotyk 5 ft): leczy zywych albo rani undead za 1d8 + modyfikator spellcasting.\n"
        "- 2 akcje (30 ft): leczy zywych albo rani undead za stale 8 HP.\n"
        "- 3 akcje (fala 30 ft): efekt obszarowy; zywi sa leczeni, undead otrzymuja positive damage."
    ),
    "paladin": (
        "Cause czempiona nastawiony na kontruderzenie. "
        "Mechanika: reakcja czempiona redukuje obrazenia sojusznika o 2 + level czempiona, "
        "a jesli napastnik jest w zasiegu, wykonujesz przeciw niemu Retributive Strike."
    ),
    "redeemer": (
        "Cause czempiona nastawiony na odkupienie i oslabianie agresji. "
        "Mechanika: reakcja czempiona redukuje obrazenia sojusznika o 2 + level czempiona; "
        "napastnik wybiera: zadaje 0 obrazen albo otrzymuje Enfeebled 2 do konca swojej nastepnej tury."
    ),
    "liberator": (
        "Cause czempiona nastawiony na wyzwolenie i mobilnosc sojusznikow. "
        "Mechanika: reakcja czempiona redukuje obrazenia sojusznika o 2 + level czempiona; "
        "sojusznik moze Step i usuwa Grabbed/Restrained."
    ),
    "iomedae": (
        "Bogini honoru, prawa i sprawiedliwej walki. "
        "Mechanika: wybor bóstwa zapisuje champion_deity=iomedae i ustawia divine skill: Intimidation."
    ),
    "sarenrae": (
        "Bogini slonca, uzdrowienia i odkupienia. "
        "Mechanika: wybor bóstwa zapisuje champion_deity=sarenrae i ustawia divine skill: Medicine."
    ),
    "torag": (
        "Bóg krasnoludow, kuznictwa i ochrony klanu. "
        "Mechanika: wybor bóstwa zapisuje champion_deity=torag i ustawia divine skill: Crafting."
    ),
    "shelyn": (
        "Bogini sztuki, milosci i piekna. "
        "Mechanika: wybor bóstwa zapisuje champion_deity=shelyn i pozwala wybrac divine skill: Crafting lub Performance."
    ),
    "desna": (
        "Bogini podrozy, gwiazd i marzen. "
        "Mechanika: wybor bóstwa zapisuje champion_deity=desna i ustawia divine skill: Acrobatics."
    ),
    "abadar": (
        "Bóg miast, handlu i porzadku spolecznego. "
        "Mechanika: wybor bóstwa zapisuje champion_deity=abadar i ustawia divine skill: Society."
    ),
    "custom": (
        "Wlasny patron czempiona ustalony przez gracza i MG. "
        "Mechanika: wybor bóstwa zapisuje champion_deity=custom i odblokowuje rozszerzona liste skilli od bóstwa "
        "(Religion, Diplomacy, Intimidation, Medicine, Society, Athletics, Crafting)."
    ),
    "acidflask": "Bomba: obrazenia od kwasu + splash.",
    "alchemists_fire": "Bomba: obrazenia od ognia + splash/persistent.",
    "bottled_lightning": "Bomba: elektryczne obrazenia i efekt pomocniczy.",
    "frost_vial": "Bomba: zimno + spowolnienie celu.",
    "tanglefoot_bag": "Bomba: utrudnia ruch celu.",
    "smokestick": "Narzedzie alchemiczne: zaslona dymna i concealed w poblizu.",
    "elixir_of_life": "Eliksir: leczenie celu.",
    "holy_water": "Consumable magic: rzut jak bomba, 1k6 good przeciw fiendom/nieumarlym.",
    "unholy_water": "Consumable magic: rzut jak bomba, 1k6 evil przeciw celestials.",
    "minor_healing_potion": "Mikstura: leczenie 1k8 HP po wypiciu.",
    "scroll_common_rank1": "Zwoj: jednorazowe rzucenie wybranego czaru 1. rangi.",
    "potency_crystal": "Talizman: +1 item do ataku bronia do konca tury.",
    "cheetahs_elixir": "Eliksir: zwieksza predkosc.",
    "eagle_eye_elixir": "Eliksir: wspiera percepcje/zasieg wzroku.",
    "juggernaut_mutagen": "Mutagen: premie obronne kosztem innych statystyk.",
    "quicksilver_mutagen": "Mutagen: premie do ataku/zasiegu kosztem wytrzymalosci.",
    "serene_mutagen": "Mutagen: premie mentalne kosztem fizycznych.",
    "cognitive_mutagen": "Mutagen: premie do testow wiedzy i intelektu.",
    "antidote": "Eliksir: premia przeciwko truciznom.",
    "antiplague": "Eliksir: premia przeciwko chorobom.",
    "arsenic": "Trucizna: naklada stan poisoned przy porazce save.",
    "giant_centipede_venom": "Trucizna: stopniowe obrazenia i pogorszenie stanu celu.",
    "acrobatics": "Akrobatyka: balans, przeciskanie i ruchy wymagajace zrecznosci.",
    "arcana": "Arkana: wiedza o magii arcane i zjawiskach magicznych.",
    "athletics": "Atletyka: wspinaczka, skoki, plywanie i silowe testy ruchu.",
    "crafting": "Rzemioslo: tworzenie i naprawa przedmiotow.",
    "deception": "Oszustwo: blef, zmylenie i kamuflowanie intencji.",
    "diplomacy": "Dyplomacja: negocjacje, wywieranie dobrego wrazenia i mediacja.",
    "intimidation": "Zastraszanie: presja, grozby i wymuszanie reakcji.",
    "medicine": "Medycyna: leczenie, diagnoza i pierwsza pomoc.",
    "nature": "Natura: wiedza o przyrodzie, zwierzetach i terenie.",
    "occultism": "Okultyzm: wiedza o zjawiskach occult i tajemnych tradycjach.",
    "performance": "Wystepy: muzyka, taniec, aktorstwo i prezentacja sceniczna.",
    "religion": "Religia: wiedza o bogach, wierzeniach i rytualach.",
    "society": "Spoleczenstwo: wiedza o kulturze, prawie i strukturach spolecznych.",
    "stealth": "Skradanie: ukrywanie sie i ciche poruszanie.",
    "survival": "Przetrwanie: orientacja w terenie, tropienie i bytowanie poza cywilizacja.",
    "thievery": "Zlodziejstwo: zamki, pulapki i zręczne manipulacje.",
    "acid_splash": (
        "Cantrip: 2 akcje, spell attack na 30 ft. "
        "Przy trafieniu zadajesz obrazenia acid; na krytyku dodatkowo nakladasz persistent acid "
        "(wartosc podawana w promptcie)."
    ),
    "acidsplash": (
        "Cantrip: 2 akcje, spell attack na 30 ft. "
        "Przy trafieniu zadajesz obrazenia acid; na krytyku dodatkowo nakladasz persistent acid "
        "(wartosc podawana w promptcie)."
    ),
    "chill_touch": (
        "Cantrip: 2 akcje, zasieg dotyk (5 ft). Cel robi Fortitude save vs Spell DC. "
        "Krytyczny sukces: 0 obrazen. Sukces: polowa obrazen negative. "
        "Porazka: pelne obrazenia i Enfeebled 1. Krytyczna porazka: podwojne obrazenia i Enfeebled 2."
    ),
    "dancing_lights": (
        "Cantrip: 2 akcje, wybierasz do 4 pol darkness/dim light w zasiegu 30 ft. "
        "Pola sa rozjasniane do konca walki."
    ),
    "daze": (
        "Cantrip: 2 akcje, cel w 60 ft robi Will save vs Spell DC. "
        "Krytyczny sukces: cel otrzymuje 1 mental damage. Sukces: polowa obrazen mental. "
        "Porazka: pelne obrazenia mental. Krytyczna porazka: pelne obrazenia mental i Stunned 1."
    ),
    "detect_magic": (
        "Cantrip: 2 akcje, skanujesz magiczne aury w pomieszczeniu. "
        "Pokazuje wykryte obiekty w zasiegu (zaleznie od poziomu), moze ujawnic ukryte magiczne obiekty."
    ),
    "detectmagic": (
        "Cantrip: 2 akcje, skanujesz magiczne aury w pomieszczeniu. "
        "Pokazuje wykryte obiekty w zasiegu (zaleznie od poziomu), moze ujawnic ukryte magiczne obiekty."
    ),
    "disrupt_undead": (
        "Cantrip: 2 akcje, tylko przeciw undead w 30 ft. Cel robi Fortitude save vs Spell DC "
        "(basic save), a ty zadajesz positive damage."
    ),
    "divine_lance": (
        "Cantrip: 2 akcje, spell attack na 30 ft. Zadaje obrazenia alignmentu bostwa castera "
        "tylko celom o przeciwnej aurze; przy krytyku obrazenia sa podwajane."
    ),
    "electric_arc": (
        "Cantrip: 2 akcje, 1 lub 2 cele. Kazdy cel robi Reflex save vs Spell DC (basic save) "
        "przeciw obrazeniom electric."
    ),
    "forbidding_ward": (
        "Cantrip: 2 akcje, wybierasz sojusznika i przeciwnika (30 ft). "
        "Sojusznik dostaje +1 status do AC i wszystkich save przeciw temu przeciwnikowi; "
        "ten przeciwnik dostaje -1 status do atakow przeciw wskazanemu sojusznikowi (1 tura)."
    ),
    "ghost_sound": (
        "Cantrip: 2 akcje, tworzysz falszywy dzwiek na wybranym polu w 30 ft "
        "(np. szept, kroki, krzyk, stukot)."
    ),
    "guidance": (
        "Cantrip: 1 akcja, sojusznik w 30 ft dostaje +1 status do atakow i testow umiejetnosci "
        "na 1 ture."
    ),
    "know_direction": "Cantrip: 1 akcja, wskazuje kierunek prawdziwej polnocy.",
    "light": "Cantrip: 2 akcje, tworzysz aure swiatla 30 ft wokol castera do konca walki.",
    "mage_hand": (
        "Cantrip: 2 akcje, interakcja z obiektem interactable (bez NPC) w zasiegu 30 ft."
    ),
    "message": (
        "Cantrip: 1 akcja, zdalna interakcja/rozmowa z celem typu NPC/interactable w zasiegu 120 ft."
    ),
    "prestidigitation": "Cantrip: 2 akcje, drobny efekt magiczny o charakterze opisowym.",
    "produce_flame": (
        "Cantrip: 2 akcje, spell attack ogniem (tryb melee 5 ft albo ranged 30 ft). "
        "Przy krytyku obrazenia sa podwajane i nakladasz persistent fire (wartosc z promptu)."
    ),
    "ray_of_frost": (
        "Cantrip: 2 akcje, spell attack na 120 ft. Zadajesz cold damage; "
        "na krytyku dodatkowo -10 ft Speed na 1 ture."
    ),
    "read_aura": (
        "Cantrip: 2 akcje, cel w 30 ft. Pokazuje aktualne statusy celu (odczyt aury)."
    ),
    "shield": (
        "Cantrip: 1 akcja, +1 circumstance do AC i absorpcja 5 obrazen do poczatku nastepnej tury."
    ),
    "shield_cantrip": (
        "Cantrip: 1 akcja, +1 circumstance do AC i absorpcja 5 obrazen do poczatku nastepnej tury."
    ),
    "sigil": (
        "Cantrip: 2 akcje, oznaczasz cel (hero/enemy/interactable) w 30 ft magicznym znakiem."
    ),
    "stabilize": (
        "Cantrip: 2 akcje, cel w 30 ft. Jesli cel ma status dying, usuwa dying i stabilizuje cel."
    ),
    "tanglefoot": (
        "Cantrip: 2 akcje, spell attack na 30 ft. Trafiony cel dostaje -10 ft Speed na 1 ture; "
        "na krytyku dodatkowo Immobilized 1."
    ),
    "telekinetic_projectile": (
        "Cantrip: 2 akcje, spell attack na 30 ft. Zadajesz obrazenia wybranego typu "
        "(bludgeoning, piercing albo slashing)."
    ),
    "additional_lore": "General feat: dodatkowe trained w wybranej specjalizacji Lore.",
    "alchemical_crafting": "General feat: pozwala tworzyc przedmioty alchemiczne.",
    "arcane_sense": "General feat: Detect Magic jako arcane innate cantrip.",
    "combat_climber": "General feat: wsparcie walki podczas wspinaczki (czesciowo opisowe).",
    "experienced_professional": "General feat: bezpieczniejszy Earn Income na Lore (opisowe).",
    "fast_recovery": "General feat: szybsze leczenie i lepsza walka z poison/disease.",
    "feather_step": "General feat: Step w difficult terrain (opisowe).",
    "fleet": "General feat: zwieksza bazowa predkosc o 5 stop.",
    "group_coercion": "General feat: Coerce wielu celow (opisowe).",
    "toughness": "General feat: zwieksza wytrzymalosc i poprawia przezywalnosc.",
    "bardic_lore": "Feat barda: Recall Knowledge przez Bardyczna wiedze (w silniku: opisowo z przewaga).",
    "lingering_composition": "Feat barda: odblokowuje Lingering Composition i zwieksza Focus Pool o 1.",
    "versatile_performance": "Feat barda: wybrane akcje spoleczne mozesz wykonywac przez Performance.",
    "true_strike": "Czar 1 rangi: przy nastepnym ataku rzucasz 2k20 i wybierasz lepszy wynik.",
    "soothe": "Czar 1 rangi: leczy cel i wzmacnia obrone przed efektami mentalnymi.",
    "unseen_servant": "Czar 1 rangi: przyzywa niewidzialnego sluge do prostych interakcji.",
    "assurance": "General feat: zapewnia staly wynik dla wybranej umiejetnosci.",
    "skill_training": "General feat: daje trained w dodatkowej umiejetnosci.",
    "quick_identification": "General feat: szybsze Identify Magic (opisowe).",
    "quick_repair": "General feat: szybsza akcja Repair (opisowe).",
    "quick_squeeze": "General feat: szybsze Squeeze (opisowe).",
    "read_lips": "General feat: czytanie z ruchu warg (opisowe).",
    "ride": "General feat: sprawniejsze dowodzenie wierzchowcem (opisowe).",
    "sign_language": "General feat: znajomosc jezykow migowych.",
    "snare_crafting": "General feat: tworzenie sidel.",
    "subtle_theft": "General feat: trudniej zauwazyc twoja kradziez (opisowe).",
    "terrain_stalker": "General feat: skradanie w wybranym trudnym terenie (opisowe).",
    "titan_wrestler": "General feat: manewry przeciw duzym celom.",
    "virtuosic_performer": "General feat: bonus do wybranego typu Performance.",
}


def localize_term_pl(value: str | None) -> str:
    raw = _normalize(value)
    if not raw:
        return ""
    direct = _LABELS_PL.get(raw)
    if direct:
        return direct
    if raw.endswith("_lore"):
        prefix = raw[: -len("_lore")]
        if prefix:
            return f"{localize_term_pl(prefix)} (Wiedza)"
    text = str(value or "").replace("_", " ").replace("-", " ").strip()
    if not text:
        return ""
    return text.title()


def _normalize_hint_format(raw: str) -> str:
    text = str(raw or "").strip()
    if not text:
        return ""
    parts = [part.strip() for part in re.split(r"\s*\|\s*", text) if part.strip()]
    if len(parts) <= 1:
        return text
    return "\n".join([parts[0]] + [f"- {part}" for part in parts[1:]])


def localized_hint_pl(value: str | None) -> str:
    raw = _normalize(value)
    if not raw:
        return ""
    return _normalize_hint_format(_HINTS_PL.get(raw, ""))
