"""Player character, monster, NPC, and actor state models."""

from .damage_affinities import DamageAffinityProfile
from .auras import ActorAura, AuraEffectKind, AuraTarget
from .features import (
    FeatureDefinition,
    FeatureGrant,
    FeatureSourceKind,
    actor_has_feature,
)
from .triggers import ActorTrigger, TriggerEffectKind, TriggerEventType
from .models import (
    AbilityScores,
    Actor,
    ActorId,
    DeathSaveState,
    Faction,
    WildShapeState,
    is_ally_or_neutral,
)
from .senses import ActorSenseProfile
from .size import (
    CREATURE_SIZE_ORDER,
    CreatureSize,
    can_grapple_or_shove_size,
    creature_size_label_pl,
    creature_size_rank,
    largest_grapple_or_shove_target,
)
from .proficiency_profile import ABILITY_NAMES, ProficiencyProfile
from .resources import (
    ActorResourcePool,
    ActorResourceRechargeResult,
    ActorResourceUseResult,
    HitDicePool,
    RecoveryPeriod,
    ResourceRechargeRule,
    actor_resource_pool,
    can_spend_actor_resource,
    depleted_recharge_resource_ids,
    resolve_actor_resource_recharge,
    spend_actor_resource,
)
from .proficiencies import (
    ability_roll_modifier,
    attack_roll_modifiers,
    proficiency_roll_modifier,
    saving_throw_modifier,
    saving_throw_roll_modifiers,
)
from .skills import (
    SKILL_ABILITIES,
    ability_check_roll_modifiers,
    passive_skill_score,
    skill_modifier,
    skill_roll_modifiers,
)
from .spell_preparation import (
    PreparableSpell,
    SpellPreparationProfile,
    prepare_spells,
    spell_is_prepared,
)
from .exhaustion import (
    ExhaustionRollKind,
    apply_exhaustion_to_roll_request,
    effective_max_hit_points,
    exhaustion_disadvantages,
    increase_exhaustion,
    reduce_exhaustion,
)
from .ranger_features import (
    NaturalExplorerBenefits,
    apply_favored_enemy_advantage,
    favored_enemy_creature_type,
    favored_enemy_humanoid_races,
    natural_explorer_benefits,
    natural_explorer_terrain,
)

__all__ = [
    "AbilityScores",
    "ABILITY_NAMES",
    "Actor",
    "ActorId",
    "ActorResourcePool",
    "ActorResourceRechargeResult",
    "ActorResourceUseResult",
    "ActorSenseProfile",
    "ActorAura",
    "ActorTrigger",
    "actor_has_feature",
    "DeathSaveState",
    "DamageAffinityProfile",
    "CreatureSize",
    "CREATURE_SIZE_ORDER",
    "Faction",
    "WildShapeState",
    "FeatureDefinition",
    "FeatureGrant",
    "FeatureSourceKind",
    "ExhaustionRollKind",
    "AuraEffectKind",
    "AuraTarget",
    "TriggerEffectKind",
    "TriggerEventType",
    "HitDicePool",
    "PreparableSpell",
    "ProficiencyProfile",
    "RecoveryPeriod",
    "ResourceRechargeRule",
    "SKILL_ABILITIES",
    "SpellPreparationProfile",
    "is_ally_or_neutral",
    "ability_roll_modifier",
    "apply_exhaustion_to_roll_request",
    "actor_resource_pool",
    "ability_check_roll_modifiers",
    "attack_roll_modifiers",
    "effective_max_hit_points",
    "exhaustion_disadvantages",
    "increase_exhaustion",
    "passive_skill_score",
    "prepare_spells",
    "proficiency_roll_modifier",
    "saving_throw_modifier",
    "saving_throw_roll_modifiers",
    "spell_is_prepared",
    "skill_modifier",
    "skill_roll_modifiers",
    "can_grapple_or_shove_size",
    "can_spend_actor_resource",
    "creature_size_label_pl",
    "creature_size_rank",
    "largest_grapple_or_shove_target",
    "NaturalExplorerBenefits",
    "apply_favored_enemy_advantage",
    "favored_enemy_creature_type",
    "favored_enemy_humanoid_races",
    "natural_explorer_benefits",
    "natural_explorer_terrain",
    "depleted_recharge_resource_ids",
    "resolve_actor_resource_recharge",
    "reduce_exhaustion",
    "spend_actor_resource",
]
