# Import wszystkich eventów, aby zarejestrować je w registry.
# Używaj poprzez `import GameObjects.events.all_events` przed dispatch.

from . import move_event  # noqa: F401
from . import stealth_event  # noqa: F401
from . import seek_event  # noqa: F401
from . import interaction_event  # noqa: F401
from . import cancel_action_event  # noqa: F401
from . import end_turn_event  # noqa: F401
from . import delay_event  # noqa: F401
from .attack import attack_sword_event  # noqa: F401
from .attack import attack_dagger_event  # noqa: F401
from .attack import attack_razortooth_jaws_event  # noqa: F401
from .attack import attack_range_long_bow  # noqa: F401
from . import raise_shield_event  # noqa: F401
from . import take_cover_event  # noqa: F401
from . import step_event  # noqa: F401
from . import leap_event  # noqa: F401
from . import prone_event  # noqa: F401
from . import stand_event  # noqa: F401
from . import command_familiar_event  # noqa: F401
from . import ancient_blood_event  # noqa: F401
from . import goblin_scuttle_event  # noqa: F401
from . import goblin_song_event  # noqa: F401
from . import aid_event  # noqa: F401
from . import grapple_event  # noqa: F401
from . import trip_event  # noqa: F401
from . import shove_event  # noqa: F401
from .magic import magic_missile_event  # noqa: F401
from .magic import detect_magic_event  # noqa: F401
from .magic import acid_splash_event  # noqa: F401
from . import phase_events  # noqa: F401
from .enemy import enemy_move_event  # noqa: F401
from .enemy import enemy_attack_melee_event  # noqa: F401
from .checks import skill_check_event  # noqa: F401
