"""Presentation and commit boundary for the Shield Bash physical-roll flow."""

from __future__ import annotations
from typing import TYPE_CHECKING

from dnd_board_game.application.shield_bash_flow import (
    ShieldBashFlow,
    submit_shield_bash_rolls,
)
from dnd_board_game.combat.session import current_actor
from dnd_board_game.combat.mana_charge import state_charge_bonus
from dnd_board_game.rules import ability_modifier, EffectEvent, EffectEventType
from dnd_board_game.world import PathResult

if TYPE_CHECKING:
    from .exploration_app import ExplorationUiSession


def shield_bash_payload(session: ExplorationUiSession) -> dict[str, object] | None:
    flow = session.shield_bash_flow
    if flow is None or session.combat_state is None:
        return None
    actor = current_actor(session.combat_state)
    target = session._actor_by_string_id(flow.target_id)
    result = flow.result
    return {
        "stage": flow.stage,
        "damage_dice": 1 + (dict(session.combat_state.shared_mana.pending_boosts).get("damage", 0) if session.combat_state.shared_mana else 0),
        "cost_note": "Potwierdzenie zużyje akcję dodatkową. Możesz też wykonać zwykły atak, jeśli masz jeszcze akcję główną. Ruch rozliczasz osobno.",
        "actor_name": actor.name,
        "target_name": target.name,
        "attacker_modifier": ability_modifier(actor.ability_scores.strength) + state_charge_bonus(session.combat_state, actor),
        "charge_bonus": state_charge_bonus(session.combat_state, actor),
        "defender_modifier": ability_modifier(target.ability_scores.strength) + state_charge_bonus(session.combat_state, target),
        "attacker_roll": flow.attacker_roll,
        "defender_roll": flow.defender_roll,
        "damage_roll": flow.damage_roll,
        "succeeded": result.succeeded if result else None,
        "attacker_total": result.attacker_total if result else None,
        "defender_total": result.defender_total if result else None,
        "damage": result.damage.damage.total_applied if result and result.damage else 0,
        "hp_before": target.hp,
        "hp_after": result.target_after.hp if result else target.hp,
        "destination": (
            list(result.push_destination.as_tuple())
            if result and result.push_destination
            else None
        ),
    }


def start_shield_bash(
    session: ExplorationUiSession, target_id: str
) -> dict[str, object]:
    if session.shield_bash_flow is not None:
        raise ValueError("Najpierw dokończ bieżące Uderzenie tarczą.")
    session.shield_bash_flow = ShieldBashFlow(target_id)
    session.board_message = "Uderzenie tarczą: wpisz k20 Garrana. Aplikacja rzuci za przeciwnika; remis wygrywa obrońca."
    session._record("shield_bash_rolls_requested", {"target_id": target_id})
    session._sync_board_leds()
    return session.state_payload()


def submit_shield_bash(
    session: ExplorationUiSession, data: dict[str, object]
) -> dict[str, object]:
    if session.shield_bash_flow is None or session.combat_state is None:
        raise ValueError("Nie ma oczekującego rzutu Uderzenia tarczą.")
    defender_roll = None
    if session.shield_bash_flow.stage == "contest":
        attacker_roll = data.get("attacker_roll")
        if type(attacker_roll) is not int or not 1 <= attacker_roll <= 20:
            raise ValueError("Podaj naturalny wynik k20 bohatera w zakresie 1–20.")
        # Enemy dice are generated by the application, never supplied by the client.
        defender_roll = session.encounter_rng.randint(1, 20)
    session.shield_bash_flow = submit_shield_bash_rolls(
        session.shield_bash_flow,
        session.combat_state,
        session._active_encounter().board,
        attacker_roll=data.get("attacker_roll"),
        defender_roll=defender_roll,
        damage_roll=data.get("damage_roll"),
    )
    session._record(
        "shield_bash_rolls_entered",
        {
            "target_id": session.shield_bash_flow.target_id,
            "attacker_roll": session.shield_bash_flow.attacker_roll,
            "defender_roll": session.shield_bash_flow.defender_roll,
            "defender_roll_source": "application",
            "damage_roll": session.shield_bash_flow.damage_roll,
            "stage": session.shield_bash_flow.stage,
        },
    )
    session.board_message = (
        f"Wygrany test Siły. Rzuć {1 + (dict(session.combat_state.shared_mana.pending_boosts).get('damage', 0) if session.combat_state.shared_mana else 0)}k6 obrażeń."
        if session.shield_bash_flow.stage == "damage"
        else "Sprawdź wynik Uderzenia tarczą i potwierdź jego zastosowanie."
    )
    session._sync_board_leds()
    return session.state_payload()


def confirm_shield_bash(session: ExplorationUiSession) -> dict[str, object]:
    flow = session.shield_bash_flow
    if flow is None or flow.stage != "result" or flow.result is None:
        raise ValueError("Najpierw wpisz rzuty i sprawdź wynik Uderzenia tarczą.")
    result = flow.result
    session.combat_state = result.state
    session.shield_bash_flow = None
    session.combat_targeting_class_feature_action_id = None
    session.combat_selected_class_feature_target_id = None
    session.combat_turn_preview_option_id = None
    damage = result.damage.damage.total_applied if result.damage else 0
    push = (
        f"Odepchnięcie na {result.push_destination.as_tuple()}."
        if result.push_destination
        else (
            "Brak odepchnięcia: pole za celem jest zablokowane."
            if result.succeeded
            else "Bez obrażeń i odepchnięcia."
        )
    )
    message = (
        f"Uderzenie tarczą: {result.attacker_total} przeciw {result.defender_total}. "
        + (
            f"Wygrana, {damage} obrażeń. "
            if result.succeeded
            else "Obrońca wygrywa (także przy remisie). "
        )
        + push
    )
    session.board_message = message
    if result.push_destination is not None:
        path = PathResult(
            result.target_before.position,
            result.target_after.position,
            (result.target_before.position, result.target_after.position),
            5,
            True,
        )
        session._apply_spike_growth_movement_damage(str(result.target_after.id), path)
        session._apply_moonbeam_entry_damage(str(result.target_after.id), path)
        session._apply_web_entry_save(str(result.target_after.id), path)
        session._apply_zone_of_truth_entry_save(str(result.target_after.id), path)
        session._apply_combat_trigger_events(
            (
                EffectEvent(
                    EffectEventType.ACTOR_MOVED,
                    actor_id=str(result.target_after.id),
                    position=result.target_after.position,
                ),
            )
        )
    session._add_message("Uderzenie tarczą", message)
    session._record(
        "shield_bash_resolved",
        {
            "target_id": flow.target_id,
            "succeeded": result.succeeded,
            "damage": damage,
            "destination": list(result.target_after.position.as_tuple()),
        },
    )
    session._sync_board_leds()
    return session.state_payload()
