"""Central Polish labels for stable rules/content identifiers."""

from __future__ import annotations


ABILITY_LABELS_PL = {
    "strength": "Siła",
    "dexterity": "Zręczność",
    "constitution": "Kondycja",
    "intelligence": "Inteligencja",
    "wisdom": "Mądrość",
    "charisma": "Charyzma",
}

SKILL_LABELS_PL = {
    "acrobatics": "Akrobatyka",
    "animal_handling": "Opieka nad zwierzętami",
    "arcana": "Wiedza tajemna",
    "athletics": "Atletyka",
    "deception": "Oszustwo",
    "history": "Historia",
    "insight": "Intuicja",
    "intimidation": "Zastraszanie",
    "investigation": "Śledztwo",
    "medicine": "Medycyna",
    "nature": "Przyroda",
    "perception": "Percepcja",
    "performance": "Występy",
    "persuasion": "Perswazja",
    "religion": "Religia",
    "sleight_of_hand": "Zwinne dłonie",
    "stealth": "Skradanie",
    "survival": "Sztuka przetrwania",
}

LANGUAGE_LABELS_PL = {
    "common": "Wspólny",
    "dwarvish": "Krasnoludzki",
    "elvish": "Elficki",
    "giant": "Olbrzymi",
    "gnomish": "Gnomi",
    "goblin": "Gobliński",
    "halfling": "Niziołczy",
    "orc": "Orkowy",
    "abyssal": "Otchłanny",
    "celestial": "Niebiański",
    "deep_speech": "Głęboka Mowa",
    "draconic": "Smoczy",
    "infernal": "Piekielny",
    "primordial": "Pierwotny",
    "sylvan": "Leśny",
    "undercommon": "Podwspólny",
}

TOOL_LABELS_PL = {
    "alchemists_supplies": "Przybory alchemika",
    "bagpipes": "Dudy",
    "brewers_supplies": "Przybory piwowara",
    "calligraphers_supplies": "Przybory kaligrafa",
    "carpenters_tools": "Narzędzia cieśli",
    "cartographers_tools": "Narzędzia kartografa",
    "cobblers_tools": "Narzędzia szewca",
    "cooks_utensils": "Przybory kucharza",
    "dice_set": "Zestaw kości",
    "disguise_kit": "Zestaw do charakteryzacji",
    "dragonchess_set": "Zestaw smoczych szachów",
    "drum": "Bęben",
    "dulcimer": "Cymbały",
    "flute": "Flet",
    "forgery_kit": "Zestaw fałszerski",
    "glassblowers_tools": "Narzędzia szklarza",
    "herbalism_kit": "Zestaw zielarza",
    "horn": "Róg",
    "jewelers_tools": "Narzędzia jubilera",
    "land_vehicles": "Pojazdy lądowe",
    "leatherworkers_tools": "Narzędzia kaletnika",
    "lute": "Lutnia",
    "lyre": "Lira",
    "masons_tools": "Narzędzia murarza",
    "navigators_tools": "Narzędzia nawigatora",
    "painters_supplies": "Przybory malarza",
    "pan_flute": "Fletnia Pana",
    "playing_card_set": "Talia kart",
    "potters_tools": "Narzędzia garncarza",
    "shawm": "Szałamaja",
    "smiths_tools": "Narzędzia kowala",
    "three_dragon_ante_set": "Zestaw Trzy Smoki",
    "thieves_tools": "Narzędzia złodziejskie",
    "tinkers_tools": "Narzędzia druciarza",
    "viol": "Wiola",
    "water_vehicles": "Pojazdy wodne",
    "weavers_tools": "Narzędzia tkacza",
    "woodcarvers_tools": "Narzędzia snycerza",
}

OPTION_LABELS_PL = {
    "archery": "Łucznictwo",
    "defense": "Obrona",
    "dueling": "Walka jedną bronią",
    "great_weapon_fighting": "Walka bronią dwuręczną",
    "one_artisans_tool_or_instrument": "Jedne narzędzia rzemieślnicze lub instrument",
    "protection": "Ochrona",
    "two_weapon_fighting": "Walka dwiema broniami",
    "bard_instruments": "Instrument muzyczny",
    "favored_enemy": "Ulubiony wróg",
    "favored_enemy_humanoid_races": "Ulubiony wróg — rasy humanoidów",
    "natural_explorer": "Naturalny odkrywca",
    "bard_instrument_bagpipes": "Dudy",
    "bard_instrument_drum": "Bęben",
    "bard_instrument_dulcimer": "Cymbały",
    "bard_instrument_flute": "Flet",
    "bard_instrument_lute": "Lutnia",
    "bard_instrument_lyre": "Lira",
    "bard_instrument_horn": "Róg",
    "bard_instrument_pan_flute": "Fletnia Pana",
    "bard_instrument_shawm": "Szałamaja",
    "bard_instrument_viol": "Wiola",
    "favored_enemy_aberration": "Aberracje",
    "favored_enemy_beast": "Bestie",
    "favored_enemy_celestial": "Niebianie",
    "favored_enemy_construct": "Konstrukty",
    "favored_enemy_dragon": "Smoki",
    "favored_enemy_elemental": "Żywiołaki",
    "favored_enemy_fey": "Fey",
    "favored_enemy_fiend": "Czarty",
    "favored_enemy_giant": "Olbrzymy",
    "favored_enemy_humanoid": "Humanoidy",
    "favored_enemy_monstrosity": "Monstrualności",
    "favored_enemy_ooze": "Szlamy",
    "favored_enemy_plant": "Rośliny",
    "favored_enemy_undead": "Nieumarli",
    "natural_explorer_arctic": "Arktyka",
    "natural_explorer_coast": "Wybrzeże",
    "natural_explorer_desert": "Pustynia",
    "natural_explorer_forest": "Las",
    "natural_explorer_grassland": "Równiny",
    "natural_explorer_mountain": "Góry",
    "natural_explorer_swamp": "Bagna",
    "natural_explorer_underdark": "Podmrok",
}

FEATURE_LABELS_PL = {
    "arcane_recovery": "Odzyskiwanie magiczne",
    "bardic_inspiration": "Inspiracja bardowska",
    "bonus_cantrip": "Dodatkowa sztuczka",
    "bonus_proficiencies": "Dodatkowe biegłości",
    "channel_divinity_sacred_weapon": "Boski Kanał: Święta broń",
    "channel_divinity_turn_the_unholy": "Boski Kanał: Odpędzenie plugawych",
    "cutting_words": "Cięta riposta",
    "dark_ones_blessing": "Błogosławieństwo Mrocznego",
    "disciple_of_life": "Uczeń życia",
    "divine_domain": "Domena boska",
    "divine_sense": "Boski zmysł",
    "draconic_resilience": "Smocza odporność",
    "dragon_ancestor": "Smoczy przodek",
    "druidic": "Druidycki",
    "evocation_savant": "Znawca wywoływania",
    "expertise": "Ekspertyza",
    "fast_hands": "Szybkie dłonie",
    "favored_enemy": "Ulubiony wróg",
    "fighting_style": "Styl walki",
    "fighting_style_archery": "Styl walki: Łucznictwo",
    "fighting_style_defense": "Styl walki: Obrona",
    "fighting_style_dueling": "Styl walki: Walka jedną bronią",
    "fighting_style_great_weapon_fighting": "Styl walki: Walka bronią dwuręczną",
    "fighting_style_protection": "Styl walki: Ochrona",
    "fighting_style_two_weapon_fighting": "Styl walki: Walka dwiema broniami",
    "frenzy": "Szał bojowy",
    "hunters_prey": "Łup myśliwego",
    "improved_critical": "Ulepszone trafienie krytyczne",
    "lay_on_hands": "Nakładanie rąk",
    "life_domain": "Domena Życia",
    "martial_arts": "Sztuki walki",
    "natural_explorer": "Naturalny odkrywca",
    "natural_recovery": "Naturalne odzyskiwanie",
    "open_hand_technique": "Technika Otwartej Dłoni",
    "otherworldly_patron": "Nadnaturalny patron",
    "pact_magic": "Magia paktu",
    "rage": "Szał",
    "sculpt_spells": "Rzeźbienie czarów",
    "second_story_work": "Praca na wysokości",
    "second_wind": "Drugi oddech",
    "sneak_attack": "Podstępny atak",
    "sorcerous_origin": "Pochodzenie czarodzieja",
    "spellcasting": "Rzucanie czarów",
    "thieves_cant": "Gwara złodziejska",
    "unarmored_defense_constitution": "Obrona bez pancerza (Kondycja)",
    "unarmored_defense_wisdom": "Obrona bez pancerza (Mądrość)",
}

SPELL_NAMES_PL = {
    "acid_arrow": "Kwasowa strzała",
    "acid_splash": "Kwasowy rozprysk",
    "aid": "Wsparcie",
    "alarm": "Alarm",
    "alter_self": "Zmiana siebie",
    "animal_friendship": "Przyjaźń ze zwierzętami",
    "animal_messenger": "Zwierzęcy posłaniec",
    "arcane_lock": "Magiczny zamek",
    "arcanists_magic_aura": "Magiczna aura arkanisty",
    "augury": "Wróżba",
    "bane": "Zguba",
    "barkskin": "Kora",
    "binding_frost": "Krępujący szron",
    "bless": "Błogosławieństwo",
    "bless_attack_bonus": "Błogosławieństwo",
    "blindness_deafness": "Ślepota/Głuchota",
    "blur": "Rozmycie",
    "branding_smite": "Piętnujące porażenie",
    "burning_hands": "Płonące dłonie",
    "call_guardian_spirit": "Wezwanie ducha strażnika",
    "calm_emotions": "Uspokojenie emocji",
    "charm_person": "Zauroczenie osoby",
    "chill_touch": "Dotyk chłodu",
    "color_spray": "Barwny rozprysk",
    "command": "Rozkaz",
    "comprehend_languages": "Rozumienie języków",
    "continual_flame": "Wieczny płomień",
    "counterspell": "Kontrczar",
    "create_or_destroy_water": "Stworzenie lub zniszczenie wody",
    "cure_wounds": "Leczenie ran",
    "dancing_lights": "Tańczące światła",
    "darkness": "Ciemność",
    "darkvision": "Widzenie w ciemności",
    "detect_evil_and_good": "Wykrycie dobra i zła",
    "detect_magic": "Wykrycie magii",
    "detect_poison_and_disease": "Wykrycie trucizny i choroby",
    "detect_thoughts": "Wykrycie myśli",
    "disguise_self": "Zmiana wyglądu",
    "divine_favor": "Boska przychylność",
    "druidcraft": "Druidztwo",
    "eldritch_blast": "Niesamowity podmuch",
    "enhance_ability": "Wzmocnienie cechy",
    "enlarge_reduce": "Powiększenie/Pomniejszenie",
    "entangle": "Oplątanie",
    "enthrall": "Urzekająca przemowa",
    "expeditious_retreat": "Szybki odwrót",
    "faerie_fire": "Baśniowy ogień",
    "false_life": "Fałszywe życie",
    "feather_fall": "Powolne opadanie",
    "find_familiar": "Przywołanie chowańca",
    "find_steed": "Przywołanie wierzchowca",
    "find_traps": "Wykrycie pułapek",
    "fire_bolt": "Ognisty pocisk",
    "flame_blade": "Ostrze płomieni",
    "flaming_sphere": "Płonąca kula",
    "floating_disk": "Lewitujący dysk",
    "fog_cloud": "Chmura mgły",
    "gentle_repose": "Łagodny spoczynek",
    "goodberry": "Dobre jagody",
    "grasping_current": "Chwytający nurt",
    "grease": "Śliskość",
    "guidance": "Wskazówki",
    "guiding_bolt": "Naprowadzający pocisk",
    "gust_of_wind": "Podmuch wiatru",
    "healing_word": "Słowo leczenia",
    "heat_metal": "Rozgrzanie metalu",
    "hellish_rebuke": "Piekielna reprymenda",
    "heroism": "Heroizm",
    "hideous_laughter": "Ohydny śmiech",
    "hold_person": "Unieruchomienie osoby",
    "hunters_mark": "Znak łowcy",
    "identify": "Identyfikacja",
    "illusory_script": "Iluzoryczne pismo",
    "inflict_wounds": "Zadawanie ran",
    "invisibility": "Niewidzialność",
    "jump": "Skok",
    "knock": "Kołatka",
    "lesser_restoration": "Pomniejsze przywrócenie",
    "levitate": "Lewitacja",
    "light": "Światło",
    "locate_animals_or_plants": "Odnalezienie zwierząt lub roślin",
    "locate_object": "Odnalezienie przedmiotu",
    "longstrider": "Długonogi",
    "mage_armor": "Zbroja maga",
    "mage_hand": "Dłoń maga",
    "magic_missile": "Magiczny pocisk",
    "magic_mouth": "Magiczne usta",
    "magic_weapon": "Magiczna broń",
    "mending": "Naprawa",
    "message": "Wiadomość",
    "minor_illusion": "Pomniejsza iluzja",
    "mirror_image": "Lustrzane odbicia",
    "misty_step": "Mglisty krok",
    "moonbeam": "Księżycowy promień",
    "pass_without_trace": "Przejście bez śladu",
    "poison_spray": "Trujący rozprysk",
    "prayer_of_healing": "Modlitwa leczenia",
    "prestidigitation": "Drobne czary",
    "produce_flame": "Stworzenie płomienia",
    "protection_from_evil_and_good": "Ochrona przed dobrem i złem",
    "protection_from_poison": "Ochrona przed trucizną",
    "purify_food_and_drink": "Oczyszczenie jadła i napoju",
    "radiant_line": "Smuga światła",
    "ray_of_enfeeblement": "Promień osłabienia",
    "ray_of_frost": "Promień mrozu",
    "repelling_pulse": "Odpychający impuls",
    "resistance": "Odporność",
    "rope_trick": "Sztuczka z liną",
    "sacred_flame": "Święty płomień",
    "sanctuary": "Sanktuarium",
    "scorching_ray": "Palący promień",
    "see_invisibility": "Widzenie niewidzialnego",
    "shatter": "Roztrzaskanie",
    "shield": "Tarcza",
    "shield_of_faith": "Tarcza wiary",
    "shillelagh": "Kostur bojowy",
    "shocking_grasp": "Porażający dotyk",
    "silence": "Cisza",
    "silent_image": "Cichy obraz",
    "sleep": "Sen",
    "spare_the_dying": "Oszczędzenie umierającego",
    "speak_with_animals": "Rozmowa ze zwierzętami",
    "spider_climb": "Pajęcza wspinaczka",
    "spike_growth": "Kolczasty wzrost",
    "spiritual_weapon": "Duchowa broń",
    "suggestion": "Sugestia",
    "thaumaturgy": "Taumaturgia",
    "thunderwave": "Fala gromu",
    "true_strike": "Pewne trafienie",
    "unravel_magic": "Rozplątanie magii",
    "unseen_servant": "Niewidzialny sługa",
    "veil_step": "Krok przez zasłonę",
    "vicious_mockery": "Zjadliwa kpina",
    "warding_bond": "Więź ochronna",
    "warding_rite": "Rytuał ochronny",
    "weakening_miasma": "Osłabiająca miazma",
    "web": "Sieć",
    "zone_of_truth": "Strefa prawdy",
}

PLAYER_LABELS_PL = {
    **ABILITY_LABELS_PL,
    **SKILL_LABELS_PL,
    **LANGUAGE_LABELS_PL,
    **TOOL_LABELS_PL,
    **OPTION_LABELS_PL,
    **FEATURE_LABELS_PL,
    **SPELL_NAMES_PL,
}


def player_label(content_id: str, fallback: str | None = None) -> str:
    if content_id in PLAYER_LABELS_PL:
        return PLAYER_LABELS_PL[content_id]
    if fallback is not None and fallback.strip():
        return fallback
    return content_id.replace("_", " ").capitalize()


__all__ = [
    "ABILITY_LABELS_PL",
    "FEATURE_LABELS_PL",
    "LANGUAGE_LABELS_PL",
    "OPTION_LABELS_PL",
    "PLAYER_LABELS_PL",
    "SKILL_LABELS_PL",
    "SPELL_NAMES_PL",
    "TOOL_LABELS_PL",
    "player_label",
]
